### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#305] opened 2016-10-19 08:46 UTC
http: panic serving   : runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc8202ed580)
	/mnt/shared/go/src/net/http/server.go:1389 +0xc1
panic(0xca2160, 0xc8200100b0)
	/mnt/shared/go/src/runtime/panic.go:443 +0x4e9
main.createKeyHandler(0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	api.go:1315 +0x141b
main.CheckIsAPIOwner.func1(0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc8205551a0, 0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	/mnt/shared/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8202f84b0, 0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	/mnt/shared/go-T/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820536ba0, 0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	/mnt/shared/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82037a980, 0x7f056c052398, 0xc820120c30, 0xc8205e9dc0)
	/mnt/shared/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8202ed580)
	/mnt/shared/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/mnt/shared/go/src/net/http/server.go:2137 +0x44e

**Comment by matiasinsaurralde** [comment] 2016-10-19 08:47
Hi, when does this error occur?

**Comment by penhauer-xiao** [comment] 2016-10-19 08:52
To Add Key  From dashboard,  it occur this panic;  And I review this code from github as below,  I think thisAPISpec is nil, so this painc have been occur.

err := thisSessionManager.UpdateSession(newKey, newSession, thisAPISpec.SessionLifetime)

**Comment by lonelycode** [comment] 2016-10-19 09:12
This is a very old bug. It has been fixed in v2.3, the issue is that the API has not been loaded into your gateway yet and so Tyk can't find the back end to publish the key to.

The trick is to wait 10s to make sure the API has been loaded by the dashboard (if the API spec is misconfigured it will also not get loaded, which can cause this error).

Restart your Tyk process and check the logs to see if the API this key is meant to target gets loaded properly.

**Comment by penhauer-xiao** [comment] 2016-10-19 10:48
I see,  It have been fixed.   
**err := thisSessionManager.UpdateSession(newKey, newSession, -1)**

**Closed** 2016-10-20 01:47 UTC
