### ISSUE TITLE
/opt/tyk-gateway/apps is a file inside the container not a folder

### ISSUE THREAD

**Issue by cverdela** [TykTechnologies/tyk#3534] opened 2021-04-23 07:16 UTC
https://github.com/TykTechnologies/tyk/issues/3521

docker hub :
tykio/tyk-gateway:v3.0.5
tykio/tyk-gateway:v3.0

whick version of tykio/tyk-gateway  should I use?

**Comment by Moses-oyedeji** [comment] 2021-06-28 13:24
@cverdela Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment] 2023-03-14 15:46
This was fixed in Tyk 3.0.5 / Tyk 3.2.0

**Closed by andyo-tyk** 2023-03-14 15:46 UTC
Labels: bug
