### ISSUE TITLE
Custom middleware removes session token metadata

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2471] opened 2019-08-27 11:51 UTC
**Branch/Envrionment/Version**
- Branch/Version: Stable 2.8 releases/Master
- Environemnt: On prem

**Describe the bug**
When Custom middleware is executed it removes session token metadata after request

**Reproduction steps**

1. Create ilija.js middleware from this task and save in {gateway_folder}/middleware/ilija.js
2. Import api definition from this task
3. Create policy with enabled access rights for api definition from task
4. Generate token with attached policy
5. Over api Update token meta data and alias from this task 
6. Trigger one call to api and check token meta tada
7. Trigger second call to api again and check token meta data

**Ilija.js middleware**

```
var postAuthMiddleware = new TykJS.TykMiddleware.NewMiddleware({});

postAuthMiddleware.NewProcessRequest(function (request, session) {
    var username = session.meta_data.username
    var password = session.meta_data.password
    var domain = session.meta_data.domain

    var newRequest = {
        "Method": "POST",
        "Headers": {"Content-Type": "application/json"},
        "Domain": domain,
        "Resource": "/qa",
        "Body": JSON.stringify({"username": username, "password": password})
    }

    try {
        var response = TykMakeHttpRequest(JSON.stringify(newRequest));

        if (response !== null) {
            // log(response)
            var parsedResponse = JSON.parse(response);
            var jsonBody = JSON.parse(parsedResponse.Body)
            if (jsonBody.token) {
                request.SetHeaders["Authorization"] = "Bearer " + jsonBody.token;
            } else {
                log("ControlM server response did not include a token: " + JSON.stringify(jsonBody))
            }

        } else {
            log("ControlM server response was null.")
        }

    } catch (err) {
        log("Error getting token from ControlM server: " + err)
    }

    return postAuthMiddleware.ReturnData(request, {})
});
```

**Api definition:**

```
{
    "id": "5d402d819633d709af0361b0",
    "name": "token-api",
    "slug": "token-api",
    "api_id": "7a64c3bb17e9472e683cd8a6c4ef2911",
    "org_id": "5d0cf05f9633d71604170227",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "pinned_public_keys": {},
    "enable_jwt": false,
    "use_standard_auth": true,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "jwt_disable_issued_at_validation": false,
    "jwt_disable_expires_at_validation": false,
    "jwt_disable_not_before_validation": false,
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {
                    "domain": "$tyk_meta.domain",
                    "pass": "$tyk_meta.password",
                    "user": "$tyk_meta.username"
                },
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/token-api/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        },
        "transport": {
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "proxy_url": ""
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [
            {
                "name": "postAuthMiddleware",
                "path": "middleware/ilija.js",
                "require_session": true
            }
        ],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {
            "AuthFailure": [
                {
                    "handler_name": "eh_web_hook_handler",
                    "handler_meta": {
                        "api_model": {},
                        "event_timeout": 60,
                        "header_map": {
                            "qa": "demo"
                        },
                        "id": "5d5d2f5d9633d70ac0bce67e",
                        "method": "POST",
                        "name": "hook",
                        "org_id": "5d0cf05f9633d71604170227",
                        "target_path": "https://webhook.site/3cc54a9e-e8c9-48bc-827d-b6605f1bb3f2",
                        "template_path": ""
                    }
                }
            ],
            "KeyExpired": [
                {
                    "handler_name": "eh_web_hook_handler",
                    "handler_meta": {
                        "api_model": {},
                        "event_timeout": 60,
                        "header_map": {
                            "qa": "demo"
                        },
                        "id": "5d5d2f5d9633d70ac0bce67e",
                        "method": "POST",
                        "name": "hook",
                        "org_id": "5d0cf05f9633d71604170227",
                        "target_path": "https://webhook.site/3cc54a9e-e8c9-48bc-827d-b6605f1bb3f2",
                        "template_path": ""
                    }
                }
            ]
        }
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "enable_ip_blacklisting": false,
    "blacklisted_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": true,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```

**Token metadata**
```
 "meta_data": {
      "BA": "QA",
      "domain": "https://httpbin.org/",
      "environment": "non-prod",
      "key_name": "api_key",
      "key_path": "tyktoken",
      "lockbox": "4dca5809-f8a3",
      "password": "qatest",
      "policy_id": "{policy id}",
      "username": "qaqa",
      "vault_role": "0c43ef90-766e-47c4-8165-2dca2ae94acb"
    },
"alias": "key:qa-server-sp:2019-08-20T11:06:16+01:00"
```

**Actual behavior**
On second request token meta data is removed from token object 

**Expected behavior**
Middleware should never delete token meta data

**Screenshots/Video**
![bug](https://user-images.githubusercontent.com/8557292/63768892-aeed0600-c8d1-11e9-843a-b4738b6102ca.gif)

**Comment by furkansenharputlu** [comment] 2019-08-28 11:46
It is not a bug. There is a problem in middleware. 
`return postAuthMiddleware.ReturnData(request, {})` should be 
`return postAuthMiddleware.ReturnData(request, session.meta_data)`. However, we need a test to see current scenario clearly. I will add it and we can close this issue.

**Closed** 2019-08-28 12:00 UTC
Labels: bug
