### ISSUE TITLE
Adding tag on key level is not saved on the key object

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1671] opened 2018-05-04 16:26 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Adding a key is not reflected in the key object 

**What is the expected behavior?**
To be shown in a similar way to the policy tag (or remove this option)
<img width="827" alt="image" src="https://user-images.githubusercontent.com/3155222/39638906-9ff0cc72-4fbf-11e8-9bcf-9666b918932c.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create an api
2. Create a key - addthe api to the key and add tag to the key
==> you'll see only the hashed tag i.e. key-{hash}

another scenario:
1. Create an api
2. Create policy and add the api and add tag
2. Create a key - add the policy to the key and add tag to the key
==> you'll see only the policy's tag

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latests was checked on the cloud

**Comment by lghiur** [comment] 2018-07-31 09:02
@letzya this is working for me, I can't reproduce it doing the steps u described. Please let me know if you still see it. @ilijabojanovic can u take a look too?

**Comment by lghiur** [comment] 2018-07-31 09:10
My bad, @ConsM explained me the bug and I see it now

**Comment by lghiur** [comment] 2018-07-31 09:38
@buger this bug can be reproduced when editing a key. If we add a new tag on an existing key the BE doesn't save it. Will assign to a BE dev

**Comment by letzya** [comment] 2019-02-20 14:49
@furkansenharputlu 
so the bug is in saving the key - add tag and open again from the “key screen”
it’s because the policy overrides the key.

**Comment by ilijabojanovic** [comment] 2019-06-26 07:11
Verified @buger please merge this in release-2.8

**Closed by ilijabojanovic** 2019-06-26 07:11 UTC
Labels: Priority: Medium, bug, customer request
