### ISSUE TITLE
transport closed before response was received error

### ISSUE THREAD

**Issue by duminhtam** [TykTechnologies/tyk#200] opened 2016-02-24 09:46 UTC
how to fix the issue `transport closed before response was received`, we increase the ulimit & tcp_tw_recycle already

**Comment by lonelycode** [comment] 2016-02-24 09:48
Can you provide a little more detail?

**Comment by mvdan** [comment] 2017-08-24 09:28
There was no more information, so I'm closing this for now. There is little we can do without knowing the cause or being able to reproduce the problem.

**Closed by mvdan** 2017-08-24 09:28 UTC
