### ISSUE TITLE
Add ARM64 job to travis file

### ISSUE THREAD

**Issue by odidev** [TykTechnologies/tyk#3313] opened 2020-09-15 12:03 UTC
**Is your feature request related to a problem? Please describe.**
Hi Team,

I am trying to add an arm64 job in Travis-ci. During this support, I found the package is using libluajit-5.1-dev. We are facing a problem in Travis due to  libluajit-5.1-dev because it does not support ARM64.

**Describe the solution you'd like**
A popular alternative to LuaJIT is MoonJIT so I have replaced libluajit-5.1-dev with MoonJIT for the arm64 job.

**Comment by Moses-oyedeji** [comment] 2021-07-01 09:55
@vverbani Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment] 2023-03-23 13:00
I'm closing this, as we no longer support Travis-CI.

**Closed by andyo-tyk** 2023-03-23 13:00 UTC
Labels: enhancement, manage-squad, zendesk
