### ISSUE TITLE
Hot restart via SIGUSR2 broken in 2.4 (regression from 2.3)

### ISSUE THREAD

**Issue by jacyo** [TykTechnologies/tyk#1268] opened 2017-11-06 03:49 UTC
Golang 1.9.2
tyk master branch

I send kill -SIGUSR2 xxx to tyk, but tyk don‘t hot restart.’

**Comment by buger** [comment] 2017-11-06 09:03
Thank you for reporting!

@jacyo by hot restart you mean reloading tyk.com config file?

**Comment by lonelycode** [comment] 2017-11-06 09:04
@buger Sending SIGUSR2 should do a fork and hot-reload

**Comment by jacyo** [comment] 2017-11-06 09:16
yes, reload tyk.conf. 
In pkg goagain, function net.FileListener return fcntl: bad file descriptor.
In setEnvs,  fd = uintptr(v.FieldByName("sysfd").Int()) is not right.

**Comment by buger** [comment] 2017-11-06 09:20
What are your operating system, CPU architecture, If you are using docker or not, and etc. Basically, anything which can help us to replicate the issue.

Thank you.

**Comment by jacyo** [comment] 2017-11-06 09:31
Ubuntu16.04, AMD64, no docker.
Operation is as follows:
go install -tags 'coprocess grpc' github.com/TykTechnologies/tyk
./bin/tyk --conf=/root/tyk/tyk.conf --httpprofile &> /root/tyk/tyk.log &
kill -SIGUSR2 4957
Log:
2017/11/06 00:47:19 goagain.go:215: user defined signal 2
2017/11/06 00:47:19 goagain.go:130: spawned child 4965
time="Nov  6 00:47:19" level=info msg="--> Using clustered mode"
time="Nov  6 00:47:19" level=info msg="Setting up analytics normaliser"
time="Nov  6 00:47:19" level=info msg="PIDFile location set to: /root/tyk-10.30/tyk.pid"
time="Nov  6 00:47:19" level=info msg="Initialising Tyk REST API Endpoints"
time="Nov  6 00:47:19" level=info msg="--> Standard listener (http)"
time="Nov  6 00:47:19" level=fatal msg="Error starting listener: listen tcp :8888: bind: address already in use"

**Comment by mvdan** [comment] 2017-11-07 11:52
@jacyo just to confirm - do the exact same steps work on 2.3.10?

**Comment by jacyo** [comment] 2017-11-08 02:42
yes, don't work on 2.3.10.

**Comment by jacyo** [comment] 2017-11-08 03:06
notice, I change to fd = uintptr(v.FieldByName("pfd").FieldByName("Sysfd").Int()) in goagain.go

**Comment by mvdan** [comment] 2017-11-15 14:52
@jacyo I see what you mean - the goagain library does indeed need updating with its reflect code.

Can reproduce on Go tip. However, note that that line only needs fixing on Go 1.9 and later. On 1.8, which is what version we'll build Tyk 2.4 with, the old line works fine.

The "address already in use" error is still there, though.

**Comment by mvdan** [comment] 2017-11-15 14:54
The main underlying issue here is that the goagain library has been unmaintained for close than three years, to the point that it's broken on the current Go release. We should probably look at alternatives for 2.5 and later, unless we want to maintain the code ourselves.

**Comment by mvdan** [comment] 2017-11-15 15:02
Confirming as a regression somewhere in 2.3, as this works fine on 2.3.2 on Go 1.8.

**Comment by mvdan** [comment] 2017-11-15 15:18
Another bit of useful info - SIGUSR2 works fine with Go 1.8 on Tyk right before that commit, as well as Tyk on any stable version (such as `2.3.12`).

**Comment by buger** [comment] 2017-11-15 15:31
Moving to 2.4.1

**Comment by mvdan** [comment] 2017-11-15 15:32
@buger we should make it clear (or at least keep it in mind) that this feature is broken in 2.4, in case any users depend on it and are surprised by the upgrade.

**Comment by buger** [comment] 2017-11-15 15:38
it is broken from 2.3.2?

**Comment by mvdan** [comment] 2017-11-15 16:04
No. It is broken since one of the earliest 2.4 commits, from back in January, that I linked above. That commit was never backported into 2.3. All 2.3 versions are fine, and 2.4 up until that commit is also fine.

**Closed** 2017-11-17 18:51 UTC
Labels: bug, Ready for development
