### ISSUE TITLE
[TD-1243]Files with secrets are readable by everyone on Linux

### ISSUE THREAD

**Issue by Exadra37** [TykTechnologies/tyk#4272] opened 2022-08-26 17:13 UTC
**Branch/Environment/Version**
- Branch/Version: master
- Environment: docker 

**Describe the bug**

Insecure file permissions used in files that contain secrets at `/opt/tyk-gateway/apps`.

**Reproduction steps**

Use this repo https://github.com/TykTechnologies/tyk-gateway-docker and start the docker stack.

```
sudo docker-compose up -d
```

Then enter the container: 

```
sudo docker-compose exec bash
```

Go to `/opt/tyk-gateway/apps`:

```
cd  /opt/tyk-gateway/apps
```

List the permissions:

```
root@09991f130e27:/opt/tyk-gateway/apps# ls -al          
total 36
drwxrwxr-x  2 1000 1000  4096 Aug 26 16:18 .
drwxr-xr-x 10 root root  4096 Aug 26 16:22 ..
-rw-rw-r--  1 1000 1000 10645 Aug 16 19:11 client-mtls-api.json
-rw-r--r--  1 root root  6342 Aug 26 16:18 httpbin.org.json
-rw-rw-r--  1 1000 1000   767 Aug 16 19:11 keyless-plugin-api.json
-rw-rw-r--  1 1000 1000   527 Aug 16 19:11 protected-api.json
```

Grep for potential places where secrets are used:

```
root@09991f130e27:/opt/tyk-gateway/apps# grep -r secret .
./client-mtls-api.json:      "shared_secret": "",
./client-mtls-api.json:        "secret": "",
./client-mtls-api.json:      "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./client-mtls-api.json:          "secret": "",
./httpbin.org.json:      "secret": "",
./httpbin.org.json:    "shared_secret": "",
./httpbin.org.json:    "secret": "",
```

Check also the shared secret for JWT:

```
root@09991f130e27:/opt/tyk-gateway/apps# grep -r jwt_source .
./client-mtls-api.json:    "jwt_source": "",
./httpbin.org.json:  "jwt_source": "h+CX0tOzd....NnqyRze3lw/WVyWrc2gZfh3XXfBOmww==",
```

**Actual behavior**

Files have insecure permissions at `/opt/tyk-gateway/apps`.

**Expected behavior**

Secure permissions on the file, ideally with access only by the root user. Better, do not store secrets on them.

**Comment by ashaparulkar** [comment] 2022-09-27 08:56
Hello @Exadra37,

Thanks for raising this issue.
We have created internal ticket to review and fix this bug.

**Comment by andyo-tyk** [comment] 2023-02-24 18:37
Hi @Exadra37,

[GitHub - TykTechnologies/tyk-gateway-docker: Docker compose deployment to run Tyk OSS Gateway](https://github.com/TykTechnologies/tyk-gateway-docker) is a demo project.

We've investigated and I can confirm that the files in `apps/` are example APIs. These are provided to get started quickly with the demo and not meant to be used in production; our assessment is that it doesn’t make sense to secure them.

I will close this ticket as "not a bug/won't fix".

Thanks for your support of Tyk!
Andy.

**Closed by andyo-tyk** 2023-02-24 18:37 UTC
Labels: bug, wontfix

**Comment by Exadra37** [comment] 2023-02-27 11:06
> [GitHub - TykTechnologies/tyk-gateway-docker: Docker compose deployment to run Tyk OSS Gateway](https://github.com/TykTechnologies/tyk-gateway-docker) is a demo project.
>
>We've investigated and I can confirm that the files in apps/ are example APIs. These are provided to get started quickly with the demo and not meant to be used in production; our assessment is that it doesn’t make sense to secure them.

I work as a Developer Advocate Fro Mobile and API Security and I can tell you for suere that this kind of examples and demos that are insecure by default its what contributes for a lot of of insecure deployements, because developers will follow them blindely or they will forget to fix the insecure default.

Please always demo your stuff with secure defaults.
