### ISSUE TITLE
Add a new middleware hook that supports trapping request and response

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1141] opened 2017-09-21 10:00 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

Add a new middleware hook that occurs at the end of the proxy chain that can support trapping both request and response.

**Comment by nickReyn** [comment] 2017-09-21 10:01
![](https://github.trello.services/images/mini-trello-icon.png) [Add a new middleware hook that supports trapping request and response](https://trello.com/c/MYBym5dM/493-add-a-new-middleware-hook-that-supports-trapping-request-and-response)

**Comment by l3ender** [comment] 2020-03-26 13:27
I believe this is a duplicate of https://github.com/TykTechnologies/tyk/issues/1526.

**Comment by andyo-tyk** [comment] 2023-03-22 15:32
Response Plugins, allowing you to modify the response object returned by the upstream, were added in Tyk 3.0 - https://tyk.io/docs/plugins/plugin-types/response-plugins/

Please feel free to re-open this ticket if you don't feel this addresses your needs.

**Closed by andyo-tyk** 2023-03-22 15:32 UTC
Labels: enhancement
