### ISSUE TITLE
Internal api usage doesn't work

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#3080] opened 2020-05-12 14:49 UTC
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: On-prem

**Describe the bug**
Internal api usage makes gateway to crash

**Reproduction steps**

1. Add api with name `first`
2. Add another api with name `second`
3. For `second`, try to set target URL as `tyk://first`
4. Make request `http://tyk-gateway:8181/second/get`

**Actual behavior**
Gateway crashes.

**Expected behavior**
It should route to the other api successfully and return result

**Comment by ilijabojanovic** [comment] 2020-05-13 08:57
This is duplicate of https://github.com/TykTechnologies/tyk/issues/2619

**Closed** 2020-05-18 13:07 UTC
Labels: bug

**Comment by ilijabojanovic** [comment] 2020-05-20 10:16
Verified
