### ISSUE TITLE
[TT-3839] Potential memory leak caused by Python middleware

### ISSUE THREAD

**Issue by tobiasb** [TykTechnologies/tyk#3720] opened 2021-11-03 23:10 UTC
**Branch/Environment/Version**
- Branch/Version: Release Tyk API Gateway v3.2.1 (`docker.tyk.io/tyk-gateway/tyk-gateway:v3.2.1`) (Also present in 3.0.1)
- Environment: On-prem

**Describe the bug**
Adding an "empty" Python middleware to an API and load testing this API causes memory usage to continuously increase without ever being released. Removing the middleware from the API prevents this from happening.

**Reproduction steps**

Create middleware:

`manifest.json`:

```
{
    "file_list": [
        "middleware.py"
    ],
    "custom_middleware": {
        "pre": [
            {
                "name": "PreHook"
            }
        ],
        "response": [
            {
                "name": "ResponseHook"
            }
        ],
        "driver": "python"
    }
}
```

`middleware.py`:

```
from tyk.decorators import Hook


@Hook
def PreHook(request, session, spec):
    return request, session


@Hook
def ResponseHook(request, response, session, metadata, spec):
    return response

```

Build middleware using Tyk docker image:

`docker run --name bundle_builder -d -v $(pwd)/app/src/:/tmp/middleware --workdir /tmp/middleware 912617429107.dkr.ecr.us-west-2.amazonaws.com/dockertykio/tyk-gateway:v3.2.1 bundle build --skip-signing -m manifest.json`

Create API:

`test.json`:

```
{
    "name": "Test Service",
    "slug": "test-service",
    "use_keyless": true,
    "api_id": "2",
    "org_id": "default",
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "3000-01-01 00:00",
                "use_extended_paths": true,
                "extended_paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                }
            }
        }
    },
    "proxy": {
        "listen_path": "/test",
        "target_url": "http://test-service",
        "strip_listen_path": true
    },
    "custom_middleware_bundle": "middleware.zip"
}
```

In this case, `test-service` is a `nginx` container serving the default HTML.

Load test API using the tool of your choice, we used Locust:

```
import urllib3
from locust import FastHttpUser, task

urllib3.disable_warnings()


class LoadTestUser(FastHttpUser):
    def on_start(self):
        self.client.verify = False

    @task
    def test(self):
        self.client.get("/test", name="/test")
```

**Actual behavior**
The memory usage of the `tyk` process inside its Docker container rises steadily, in this case about 4.5MB/min, and never comes down (light blue graph), even after aborting the load test (test stopped at around 22:30 mark).

![image](https://user-images.githubusercontent.com/54142/140230794-835a9452-76dd-40d7-a0f1-a7b92e446006.png)

**Expected behavior**
It would be nice if the memory usage didn't rise steadily or at least went down after a period of high throughput. This is the graph for the exact same setup, the only difference being that I removed the `"custom_middleware_bundle": "middleware.zip"` from the API definition in the `test.json`.

![image](https://user-images.githubusercontent.com/54142/140230915-42b49583-ca29-47e9-8367-a50aecd19dcf.png)

**Logs (debug mode or log file):**
```
time="Nov 03 20:39:29" level=info msg="Tyk API Gateway v3.2.1" prefix=main
time="Nov 03 20:39:29" level=warning msg="Insecure configuration allowed" config.allow_insecure_configs=true prefix=checkup
time="Nov 03 20:39:29" level=warning msg="Default secret should be changed for production." config.secret=... prefix=checkup
time="Nov 03 20:39:29" level=info msg="PIDFile location set to: /var/run/tyk/tyk-gateway.pid" prefix=main
time="Nov 03 20:39:29" level=warning msg="The control_api_port should be changed for production" prefix=main
time="Nov 03 20:39:29" level=info msg="Initialising Tyk REST API Endpoints" prefix=main
time="Nov 03 20:39:29" level=info msg="Starting Poller" prefix=host-check-mgr
time="Nov 03 20:39:29" level=info msg="--> Standard listener (http)" port=":8000" prefix=main
time="Nov 03 20:39:29" level=warning msg="Starting HTTP server on:[::]:8000" prefix=main
time="Nov 03 20:39:29" level=info msg="Initialising distributed rate limiter" prefix=main
time="Nov 03 20:39:29" level=info msg="Tyk Gateway started (v3.2.1)" prefix=main
time="Nov 03 20:39:29" level=info msg="--> Listening on address: (open interface)" prefix=main
time="Nov 03 20:39:29" level=info msg="--> Listening on port: 8000" prefix=main
time="Nov 03 20:39:29" level=info msg="--> PID: 1" prefix=main
time="Nov 03 20:39:29" level=info msg="Loading policies" prefix=main
time="Nov 03 20:39:29" level=info msg="Policies found (1 total):" prefix=main
time="Nov 03 20:39:29" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json"
time="Nov 03 20:39:29" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/test.json"
time="Nov 03 20:39:29" level=info msg="Detected 2 APIs" prefix=main
time="Nov 03 20:39:29" level=info msg="Loading API configurations." prefix=main
time="Nov 03 20:39:29" level=info msg="Tracking hostname" api_name="Tyk Test API" domain="(no host)" prefix=main
time="Nov 03 20:39:29" level=info msg="Tracking hostname" api_name="Test Service" domain="(no host)" prefix=main
time="Nov 03 20:39:29" level=info msg="Initialising Tyk REST API Endpoints" prefix=main
time="Nov 03 20:39:29" level=info msg="API bind on custom port:0" prefix=main
time="Nov 03 20:39:29" level=info msg="Checking security policy: Token" api_id=1 api_name="Tyk Test API" org_id=default
time="Nov 03 20:39:29" level=info msg="API Loaded" api_id=1 api_name="Tyk Test API" org_id=default prefix=gateway server_name=-- user_id=-- user_ip=--
time="Nov 03 20:39:29" level=info msg="API bind on custom port:0" prefix=main
time="Nov 03 20:39:29" level=info msg="Starting gateway rate limiter notifications..."
time="Nov 03 20:39:29" level=info msg="--> [REDIS] Creating single-node client"
time="Nov 03 20:39:29" level=info msg="----> Fetching Bundle: middleware.zip" prefix=main
time="Nov 03 20:39:29" level=info msg="----> Loading bundle: middleware.zip" prefix=main
time="Nov 03 20:39:29" level=info msg="----> Verifying bundle: middleware.zip" prefix=main
time="Nov 03 20:39:29" level=info msg="----> Bundle is valid, adding to spec: middleware.zip" prefix=main
time="Nov 03 20:39:29" level=info msg="--> [REDIS] Creating single-node client"
time="Nov 03 20:39:29" level=info msg="--> [REDIS] Creating single-node client"
time="Nov 03 20:39:29" level=info msg="Python version '3.7' loaded" prefix=coprocess
time="Nov 03 20:39:30" level=info msg="Initializing dispatcher" prefix=python
time="Nov 03 20:39:30" level=info msg="Python dispatcher was initialized" prefix=coprocess
time="Nov 03 20:39:30" level=info msg="Loading module: '2_cf6a4cfa182dfb7c4201a6181a85f32d'" prefix=python
time="Nov 03 20:39:30" level=info msg="Checking security policy: Open" api_id=2 api_name="Test Service" org_id=default
time="Nov 03 20:39:30" level=info msg="API Loaded" api_id=2 api_name="Test Service" org_id=default prefix=gateway server_name=-- user_id=-- user_ip=--
time="Nov 03 20:39:30" level=info msg="Loading uptime tests..." prefix=host-check-mgr
time="Nov 03 20:39:30" level=info msg="Initialised API Definitions" prefix=main
time="Nov 03 20:39:30" level=info msg="API reload complete" prefix=main
time="Nov 03 20:39:39" level=warning msg="Reconnecting storage: Redis is either down or ws not configured" prefix=pub-sub
```

**Configuration (tyk config file):**
```
{
  "listen_port": 8000,
  "secret": "<REMOVED>",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "redis-tyk",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  },
  "enable_analytics": false,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "optimisations_use_async_session_write": true,
  "enable_non_transactional_rate_limiter": true,
  "enable_sentinel_rate_limiter": false,
  "enable_redis_rolling_limiter": false,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/opt/tyk-gateway/policies/policies.json"
  },
  "hash_keys": true,
  "close_connections": false,
  "http_server_options": {
    "enable_websockets": true,
    "read_timeout": 300,
    "write_timeout": 300
  },
  "allow_insecure_configs": true,
  "coprocess_options": {
    "enable_coprocess": true,
    "coprocess_grpc_server": "",
    "python_path_prefix": "/opt/tyk-gateway"
  },
  "enable_bundle_downloader": true,
  "bundle_base_url": "http://bundle-provider",
  "global_session_lifetime": 100,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 500,
  "log_level": "info",
  "proxy_default_timeout": 300
}

```

**Comment by agata-wit** [comment] 2021-11-08 10:45
@tobiasb thanks for contributing! If you don't mind me asking - what's your use case here? Why would you add "empty" Py middleware?

**Comment by tobiasb** [comment] 2021-11-08 15:43
That's the minimal example without all our business logic which I thought would make it easier for you to investigate this issue. I thought at first that the problem was in our own logic but then stripped away more and more of our code until there was only the bare middleware scaffolding left and the container is still leaking memory. That's why I'm wondering if the problem is within Tyk or the Python middleware framework.

**Comment by agata-wit** [comment] 2021-11-08 16:41
Got it, thanks for explaining. It just seemed strange someone would upload an "empty" plugin but I understand the context now and how this came about.
I will take it away to investigate with the team, I'll let you know our findings once we replicate and triage.

**Comment by letzya** [comment] 2021-11-08 21:28
Yeh, it's not empty but just the bare minimum

**Comment by mhuaco** [comment] 2021-11-09 22:34
Hello tobiasb

We are looking into it and will provide an update as soon as it becomes available.

Ticket open:
https://tyktech.atlassian.net/browse/TT-3839

**Comment by tobiasb** [comment] 2021-11-09 22:36
I hope you are able to reproduce it. 
Thank you very much, I appreciate it.

**Comment by tobiasb** [comment] 2021-11-18 22:01
Hello @mhuaco, would you have an update for me by any chance? Were you able to reproduce the issue at all? Thanks.

**Comment by tobiasb** [comment] 2021-11-23 18:08
From https://community.tyk.io/t/potential-memory-leak-caused-by-python-middleware-3720/5053

```
Hi,

The internal ticket linked which you are unable to access is still in our backlog awaiting engineering review and actioning. As a result we cannot offer any timeline as to when it will be addressed, but we’ll revise the GH issue when necessary.

Best Regards,
Chris
```

**Comment by andyo-tyk** [comment] 2023-08-16 15:48
Hi @tobiasb,
Do you still see this issue with latest Tyk versions? We have made many improvements since 3.2.1 and believe this should no longer be an issue.
Thanks!

**Comment by tobiasb** [comment] 2023-08-16 17:35
I'm no longer with the org so I'm unable to check but thanks for reaching out.

**Comment by andyo-tyk** [comment] 2023-10-16 15:07
I'm closing this as no longer reproducible.

**Closed by andyo-tyk** 2023-10-16 15:07 UTC
Labels: bug, manage-squad
