### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by hellojukay** [TykTechnologies/tyk#1368] opened 2017-12-19 10:11 UTC
**Do you want to request a *feature* or report a *bug*?**
report bug
**What is the current behavior?**
when i get free License, i got three email of License. the license are different,which one should i should , i try three times use the three diffrent license. but error.

<img width="1076" alt="fuck" src="https://user-images.githubusercontent.com/10371891/34151797-74d91f46-e4e7-11e7-9d35-0c11171813e8.png">

how can i login dashboard?? any one can help me?
![fuck2](https://user-images.githubusercontent.com/10371891/34151932-dd04a48c-e4e7-11e7-8301-b4c25d4e937b.png)

**Comment by ConsM** [comment] 2017-12-19 10:13
How have you installed Tyk ? I assume this is On Premise ?

**Comment by hellojukay** [comment] 2017-12-19 10:16
@ConsM 

```shll
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                              NAMES
bada91f1ec0d        tykio/tyk-dashboard   "/opt/tyk-dashboard/t"   13 minutes ago      Up 13 minutes       0.0.0.0:3000->3000/tcp, 5000/tcp   tyk_dashboard
da708ab5b54f        tutum/mongodb         "/run.sh"                About an hour ago   Up About an hour    27017/tcp, 28017/tcp               boring_almeida
f4e9771e9866        tykio/tyk-gateway     "./entrypoint.sh"        About an hour ago   Up About an hour    0.0.0.0:8080->8080/tcp             tyk_gateway
c0b2e4bb6f9c        redis                 "docker-entrypoint.sh"   About an hour ago   Up About an hour    6379/tcp                           tyk_redis
```

**Comment by hellojukay** [comment] 2017-12-19 10:16
i install tyk by docker

**Comment by hellojukay** [comment] 2017-12-19 10:19
this is the conf ,i copy from github.
```json
{
  "listen_port": 8080,
  "secret": "352d20ee67be67f6340b4c0605b044b7",
  "template_path": "/opt/tyk-gateway/templates",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 7379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  },
  "enable_analytics": false,
  "analytics_config": {
    "type": "csv",
    "pool_size": 100,
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": [],
    "normalise_urls": {
        "enabled": true,
        "normalise_uuids": true,
        "normalise_numbers": true,
        "custom_patterns": []
    }
  },
  "health_check": {
    "enable_health_checks": false,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "allow_master_keys": false,
  "policies": {
  	"policy_source": "file",
  	"policy_record_name": "policies"
    },
  "hash_keys": true,
  "suppress_redis_signal_reload": false,
  "close_connections": true,
  "enable_non_transactional_rate_limiter": true,
  "enable_sentinel_rate_limiter": false,
  "local_session_cache": {
    "disable_cached_session_state": false
  },
  "uptime_tests": {
    "disable": false,
    "config": {
      "enable_uptime_analytics": false,
      "failure_trigger_sample_size": 2,
      "time_wait": 10,
      "checker_pool_size": 50
    }
  },
  "http_server_options": {
        "enable_websockets": true
  },
  "hostname": "",
  "enable_custom_domains": true,
  "enable_jsvm": true,
  "oauth_redirect_uri_separator": ";",
  "coprocess_options": {
    "enable_coprocess": false,
    "coprocess_grpc_server": ""
  },
  "pid_file_location": "./tyk-gateway.pid",
  "allow_insecure_configs": true,
  "public_key_path": "",
  "close_idle_connections": false,
  "allow_remote_config": false,
  "enable_bundle_downloader": true,
  "bundle_base_url": "",
  "global_session_lifetime": 100,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 100
}
```

**Comment by ConsM** [comment] 2017-12-19 10:22
Ok, this is not a bug though. 
The right place to get help for this would be the [community forum](https://community.tyk.io/), I will close this issue so please open a new topic there and we'll be happy to help you debug your issue.
In the meanwhile the credentials you should use to login to your Dashboard are the ones that are generated by the `setup` script in step 4.

**Closed by ConsM** 2017-12-19 10:22 UTC
