### ISSUE TITLE
Getting panic when trying to retrieve OIDC signature verification key

### ISSUE THREAD

**Issue by wonderslug** [TykTechnologies/tyk#288] opened 2016-08-17 19:47 UTC
Howdy

Im trying to get tyk-gateway to validate against an OIDC access key.  But im getting a panic in openid2go when its called to try to get the JWK signature verification key.  But its odd because I get the panic only every 2nd call.  The other call is still giving me "Key not authorised"

This is with gateway 2.2.0.3 being run form the docker image

The Panic

```
2016/08/17 19:50:51 http: panic serving 192.168.99.1:52583: interface conversion: interface is nil, not string
goroutine 85 [running]:
net/http.(*conn).serve.func1(0xc82046a300)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xd2c9e0, 0xc8204b92c0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/TykTechnologies/openid2go/openid.(*idTokenValidator).renewAndGetSigningKey(0xc8203737a0, , 0x0, 0x0, 0x0)
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/idtokenvalidator.go:60 +0x23a
github.com/TykTechnologies/openid2go/openid.(*idTokenValidator).(github.com/TykTechnologies/openid2go/tSigningKey)-fm(0xc8200e2500, 0x0, 0x0, 0x0, 0x0)
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/idtokenvalidator.go:38 +0x46
github.com/dgrijalva/jwt-go.(*Parser).ParseWithClaims(0xc820140a70, 0xc820387087, 0x567, 0x7ffb6311bda8, 8200dc1a0, 0x0, 0x0, 0x0)
    /home/tyk/go/src/github.com/dgrijalva/jwt-go/parser.go:96 +0x12c3
github.com/dgrijalva/jwt-go.(*Parser).Parse(0xc820140a70, 0xc820387087, 0x567, 0xc8200dc1a0, 0xc8200e24b0, 
    /home/tyk/go/src/github.com/dgrijalva/jwt-go/parser.go:19 +0xb4
github.com/dgrijalva/jwt-go.Parse(0xc820387087, 0x567, 0xc8200dc1a0, 0xc8200e24b0, 0x0, 0x0)
    /home/tyk/go/src/github.com/dgrijalva/jwt-go/token.go:89 +0x6a
github.com/TykTechnologies/openid2go/openid.(*idTokenValidator).validate(0xc8203737a0, 0xc820387087, 0x567, 
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/idtokenvalidator.go:38 +0x141
github.com/TykTechnologies/openid2go/openid.authenticate(0xc820373760, 0x7ffb6311bd48, 0xc8203b4b60, 82038a030, 0x7)
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/middleware.go:115 +0x117
github.com/TykTechnologies/openid2go/openid.authenticateUserWithToken(0xc820373760, 0x7ffb6311bd48, 8204ee460, 0x0, 0x0, 0x13f0ea8)
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/middleware.go:157 +0x5e
github.com/TykTechnologies/openid2go/openid.AuthenticateOIDWithUser(0xc820373760, 0x7ffb6311bd48, 8204ee460, 0xbca660, 0xc8200e7818, 0x0)
    /home/tyk/go/src/github.com/TykTechnologies/openid2go/openid/middleware.go:91 +0x3f
main.(*OpenIDMW).ProcessRequest(0xc820373740, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460, 0x0, 0x0, 0x0, 0x0, 
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware_openid.go:91 +0xb3
main.CreateMiddleware.func1.1(0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:44 +0x178
net/http.HandlerFunc.ServeHTTP(0xc8203926c0, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
main.CreateMiddleware.func1.1(0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:61 +0x38b
net/http.HandlerFunc.ServeHTTP(0xc820392700, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
main.CreateMiddleware.func1.1(0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:61 +0x38b
net/http.HandlerFunc.ServeHTTP(0xc820392740, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
main.CreateMiddleware.func1.1(0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:61 +0x38b
net/http.HandlerFunc.ServeHTTP(0xc820392780, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
main.CreateMiddleware.func1.1(0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:61 +0x38b
net/http.HandlerFunc.ServeHTTP(0xc8203927c0, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820274c80, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820010e70, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820363380, 0x7ffb6311bd48, 0xc8203b4b60, 0xc8204ee460)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82046a300)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

The non-panic response:

```
time="Aug 17 19:32:36" level=warning msg="JWT Invalid: Validation error. Jwt token validation failed."
time="Aug 17 19:32:36" level=warning msg="Attempted access with invalid key." key="[JWT]"
time="Aug 17 19:32:36" level=error msg="request error: Key not authorised" api_id=1 org_id=1 path="/ip" server_name="http://httpbin.org/" user_id= user_ip=192.168.99.1
```

The API is has the following config

```
{
  "name": "Test API",
  "slug": "test-api",
  "api_id": "1",
  "org_id": "1",
  "auth": {
    "auth_header_name": "Authorization"
  },
  "definition": {
    "location": "header",
    "key": "x-api-version"
  },
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default",
        "use_extended_paths": true
      }
    }
  },
  "proxy": {
    "listen_path": "/test-api/",
    "target_url": "http://httpbin.org/",
    "strip_listen_path": true
  },
  "active": true,
  "use_openid": true,
  "openid_options": {
    "providers": [
      {
        "issuer": "https://out-keycloak-url/auth/realms/adfs",
        "client_ids": {
          "c2FtcGxlX2xvZ2lu": "default"
        }
      }
    ],
    "segregate_by_client": false
  }
}
```

Im using Keycloak as the OIDC provider and I have it working elsewhere.

**Comment by lonelycode** [comment] 2016-08-17 20:08
It might actually be the JWK - the reason yu get a panic on the second response is because the cache is being flushed and a new correct validation is returned - it's a bug in the openid lib. 

We'd need to look at the JWK to be sure though.

**Comment by wonderslug** [comment] 2016-08-17 20:13
OK cool,

The https://our-keycloak-url/auth/realms/adfs/.well-known/openid-configuration is 
```json
{
  issuer: "https://our-keycloak-url/auth/realms/adfs",
  authorization_endpoint: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/auth",
  token_endpoint: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/token",
  token_introspection_endpoint: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/token/introspect",
  userinfo_endpoint: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/userinfo",
  end_session_endpoint: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/logout",
  jwks_uri: "https://our-keycloak-url/auth/realms/adfs/protocol/openid-connect/certs",
  grant_types_supported: [
    "authorization_code",
    "implicit",
    "refresh_token",
    "password",
    "client_credentials"
  ],
  response_types_supported: [
    "code",
    "none",
    "id_token",
    "token",
    "id_token token",
    "code id_token",
    "code token",
    "code id_token token"
  ],
  subject_types_supported: [
    "public"
  ],
  id_token_signing_alg_values_supported: [
    "RS256"
  ],
  response_modes_supported: [
    "query",
    "fragment",
    "form_post"
  ],
  registration_endpoint: "https://our-keycloak-url/auth/realms/adfs/clients-registrations/openid-connect"
}
```

and the JWKS is like this
```json
{
  keys: [
    {
      kid: "pB0hjCKD-DW-b5edo5iV-Qviy5FCcAaTRJFUo59p5xg",
      kty: "RSA",
      alg: "RS256",
      use: "sig",
      n: "rc5r5-2RC2HqZ8cSTPL4wwCv7-BOrJp4gU3CsFkeZD05pSMO-t3SisUnmtswWOzK6CDjRncC46uo8993-h7VKm2Paiiu5oRpLqhZnZxBSFgTm0GTdvVxoFWHtLTLmqdKN_O9cOXiGaH6dfj_ykvgwuE2OYg9hciREqa7gJ6ijY1EuWYCdeh52-TnsKJEElYs4LmqyIw5NaaH80PwQAq2--LUNWCjfE6TIUqyng3jFbrYAqwJNm-T9GmdvQhmERXsW5iPxBlFHxLnPmg2dBlZvx_UsG64CrZ51yl4SMsSUUqrVxnR58XF7GisG7kjlpiZ05LzL59K5PbEUts4-olmEQ",
      e: "AQAB"
    }
  ]
}
```

**Comment by lonelycode** [comment] 2016-08-17 20:36
Thanks - leave it with us and we'll investigate :-)

**Comment by lonelycode** [comment] 2016-08-17 21:42
I've pushed a fix for the OIDC lib that at least should remove the type error causing the panic you're seeing. Still trying to get a handle on why it's failing. The panic is essentially that Tyk can't find the `kid` field in the JWK for the issuer.

**Comment by kohrVid** [comment] 2017-01-23 16:26
Hi Brian,

The bug you reported last August was fixed in a patch release and shouldn't appear in the latest version of Tyk. Could you please confirm as to whether you're still getting these errors? If you aren't, would it be all right if we closed this issue on Github?

Kind regards,
Jess

**Comment by mvdan** [comment] 2017-02-16 14:21
@wonderslug I'm closing this issue now - if you're still having the same problem or would like any more help, feel free to reopen with more information.

Thanks.

**Comment by ChristianCiach** [comment] 2017-06-27 13:43
I can't get this to work with Keycloak, too. 

The log says this:
```
time="Jun 27 15:38:28" level=warning msg="JWT Invalid: Validation error. Jwt token validation failed." 
time="Jun 27 15:38:28" level=warning msg="Attempted access with invalid key." key="[JWT]" 
time="Jun 27 15:38:28" level=error msg="request error: Key not authorised" api_id=1 org_id= path="/test-api/version" server_name="http://apigate.local:10082/" user_id= user_ip=127.0.0.1 
```

This is the id_token:

`eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJOVnJoc2NYb3JDbVFzTnk3TTNwdmFTSmtWUVVYXzljcXVJc0tmVzJpSzNnIn0.eyJqdGkiOiI5NzA0Y2YzMi0wODBmLTRjM2YtYjQ2YS1mYTQ4OTY3MTdkOTYiLCJleHAiOjE0OTg1NjIxNzIsIm5iZiI6MCwiaWF0IjoxNDk4NTYxODcyLCJpc3MiOiJodHRwOi8vbG9naW4uaHViLmRldmVsb3BtZW50LmVtcy9hdXRoL3JlYWxtcy92a3Rlc3QiLCJhdWQiOiJhcGktZ2F0ZXdheSIsInN1YiI6Ijg0ZmRjNDUyLWNkNzItNDZiMC04YWU3LTVkYjZiOWVhODJmNiIsInR5cCI6IklEIiwiYXpwIjoiYXBpLWdhdGV3YXkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJlZjdhM2U1MC0xZTdlLTQ2ZDgtYWE4Yi03MDBkOGNmNDBlNTIiLCJhY3IiOiIxIiwibmFtZSI6IkNocmlzdGlhbiBDaWFjaCIsInByZWZlcnJlZF91c2VybmFtZSI6ImNocmlzdGlhbmMiLCJnaXZlbl9uYW1lIjoiQ2hyaXN0aWFuIiwiZmFtaWx5X25hbWUiOiJDaWFjaCIsImVtYWlsIjoiY2hyaXN0aWFuLmNpYWNoQGVuZXJneW1ldGVvLmRlIn0.KlKk81JiRn2INluMQk6CQ_wN9_pzL85AKwa2lDpN_ifjdfVCC_UUR69Rz39f1t7JkYm1AEbiavo8TOADftzxSsJ8a-ygPotmQp7IwrC6jB9KKLlMpudtdBYb-LfgqCfAuYDh74typNinOgXwbyJApugiOHkz95ndv2yJV4WZC8Qv5xvXvNZobceUXjyd3vSQrtJjr02vwuEhiyfpEhD-t6NTNNCYjUWjPYiaDpL-20Pm_mdPoDTtG429UQFN3eqm7_gdUB2w4Plor0r7rK3nJrWIRTI7W2qr_Ym6gx_Okb5IflYm9R-0m2xpfcvo53lTxEwXrh14ws0xeNDepIlHAQ`

The JWKS returned by Keycloak is this (pretty printed for your convenience):

```
{
  "keys": [
    {
      "kid": "NVrhscXorCmQsNy7M3pvaSJkVQUX_9cquIsKfW2iK3g",
      "kty": "RSA",
      "alg": "RS256",
      "use": "sig",
      "n": "23E1vt5aJwFvEnyJl2AW2z8GhwJwwrWntm2hdQkB4JYkz8pwz3zNxlJBU5EhAsI5C2pYeeEwCIhjt2MfxcsokMT1NioFzzGd2PzslrFmddbtDGitiYjqXupWcNd2qy2Rgw_O33flspXjifraAklDaoLzDDVyEUdrCJ7SB1HfxsuDsvuZINR6jRowPut-e-r0nif57ry_xQZ5SZq9ShKfZd7KbIijLb_LHgAXgU3E4Tb9R43gIpD2282RionIWiBmUXKeThQVVOgsooVDhnmyCLtHNq2FQ2K0FczF5sUyN3ufpdr1dfrhkzv560BlkGzBljpeh8uAsZs0IazAsek1-Q",
      "e": "AQAB"
    }
  ]
}
```

I know that the token is valid. I can validate it just fine with my own java application. I am happy to provide additional information if you need them.

**Comment by ChristianCiach** [comment] 2017-06-27 15:06
Is there a chance that the fix gets backported to the 2.3 branch? I am currently evaluating different API gateways for my organization and OpenID Connect is a must have. If I can't get this to work with Tyk in the near future I am forced to use another gateway.

**Comment by buger** [comment] 2017-06-27 15:09
We are investigating your issue. In meantime can you share your API definition?

**Comment by ChristianCiach** [comment] 2017-06-27 16:07
Of course, here you go:

```
{
      "name": "emsys-api",
      "api_id": "1",
      "use_openid": true,
      "openid_options": {
        "providers": [
          {
            "issuer": "http://login.hub.development.ems/auth/realms/vktest",
            "client_ids": {
              "YXBpLWdhdGV3YXk=": "default"
            }
          }
        ],
	"segregate_by_client": false
      },
      "version_data": {
          "not_versioned": true,
          "versions": {
              "Default": {
                  "name": "Default",
                  "use_extended_paths": true
              }
          }
      },
      "proxy": {
          "listen_path": "/test-api/",
          "target_url": "http://apigate.local:10082/",
          "strip_listen_path": true
      },
      "active": true
}
```

**Comment by buger** [comment] 2017-06-28 07:29
And your policy is named "default" and it have access to this API?

Asking because there can be some confusion here. When you configure OpenID you need to specify policy when creating the API, because keys are created dynamically, and this policy will be applied to all the OID keys. Problem is that you can't create this policy before unless you have API... :)

So when you define OpenID API you first create it without policy, then you create a policy with this API, and after you can modify API to include policy ID. Well, at least thas how it works when you use Dashboard. 

I'm right that you are using Tyk without Dashboard?

**Comment by ChristianCiach** [comment] 2017-06-28 07:35
Yes, I am using Tyk without the dashboard for my evaluation. We may upgrade to an edition with dashboards if I can get this to work. 

Also, I have defined a policy called "default". I am not at work right now, but I will show you my policy file in about an hour. Thanks for your help this far!

**Comment by james-tyk** [comment] 2017-06-28 07:51
Just a note @ChristianCiach - Tyk dashboard is free for a single-gateway deployment, even for commercial use in production, so you can use the dashboard as part of your evaluation if you wish.

**Comment by ChristianCiach** [comment] 2017-06-28 08:24
@james-tyk 
Thanks, I know :) Thing is, the Tyk-Gateway would be deployed and configured automatically via Ansible, so it must at least work without the dashboard. We would use the dashboard primarily for monitoring and emergency configuration changes, like revoking accesses.

**Comment by ChristianCiach** [comment] 2017-06-28 08:34
@buger 
This is my policies.json:

```
{
        "default": {
                "rate": 1000,
                "per": 1,
                "quota_max": 100,
                "quota_renewal_rate": 60,
                "access_rights": {
                        "41433797848f41a558c1573d3e55a410": {
                                "api_name": "emsys-api",
                                "api_id": "1",
                                "versions": [
                                        "Default"
                                ]
                        }
                },
                "hmac_enabled": false
        }
}
```

When I make a request these are the request and response headers:

```
10:28:55.036[27ms][total 27ms] Status: 403[Forbidden]
GET http://apigate.local:8080/test-api/version Load Flags[LOAD_BACKGROUND  LOAD_BYPASS_LOCAL_CACHE_IF_BUSY ] Größe des Inhalts[37] Mime Type[application/json]
   Request Header:
      Host[apigate.local:8080]
      User-Agent[Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0]
      Accept[*/*]
      Accept-Language[en-US,en;q=0.5]
      Accept-Encoding[gzip, deflate]
      Authorization[Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJOVnJoc2NYb3JDbVFzTnk3TTNwdmFTSmtWUVVYXzljcXVJc0tmVzJpSzNnIn0.eyJqdGkiOiI5NzA0Y2YzMi0wODBmLTRjM2YtYjQ2YS1mYTQ4OTY3MTdkOTYiLCJleHAiOjE0OTg1NjIxNzIsIm5iZiI6MCwiaWF0IjoxNDk4NTYxODcyLCJpc3MiOiJodHRwOi8vbG9naW4uaHViLmRldmVsb3BtZW50LmVtcy9hdXRoL3JlYWxtcy92a3Rlc3QiLCJhdWQiOiJhcGktZ2F0ZXdheSIsInN1YiI6Ijg0ZmRjNDUyLWNkNzItNDZiMC04YWU3LTVkYjZiOWVhODJmNiIsInR5cCI6IklEIiwiYXpwIjoiYXBpLWdhdGV3YXkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJlZjdhM2U1MC0xZTdlLTQ2ZDgtYWE4Yi03MDBkOGNmNDBlNTIiLCJhY3IiOiIxIiwibmFtZSI6IkNocmlzdGlhbiBDaWFjaCIsInByZWZlcnJlZF91c2VybmFtZSI6ImNocmlzdGlhbmMiLCJnaXZlbl9uYW1lIjoiQ2hyaXN0aWFuIiwiZmFtaWx5X25hbWUiOiJDaWFjaCIsImVtYWlsIjoiY2hyaXN0aWFuLmNpYWNoQGVuZXJneW1ldGVvLmRlIn0.KlKk81JiRn2INluMQk6CQ_wN9_pzL85AKwa2lDpN_ifjdfVCC_UUR69Rz39f1t7JkYm1AEbiavo8TOADftzxSsJ8a-ygPotmQp7IwrC6jB9KKLlMpudtdBYb-LfgqCfAuYDh74typNinOgXwbyJApugiOHkz95ndv2yJV4WZC8Qv5xvXvNZobceUXjyd3vSQrtJjr02vwuEhiyfpEhD-t6NTNNCYjUWjPYiaDpL-20Pm_mdPoDTtG429UQFN3eqm7_gdUB2w4Plor0r7rK3nJrWIRTI7W2qr_Ym6gx_Okb5IflYm9R-0m2xpfcvo53lTxEwXrh14ws0xeNDepIlHAQ]
      Connection[keep-alive]
   Response Header:
      Connection[close]
      Content-Type[application/json]
      X-Generator[tyk.io]
      Date[Wed, 28 Jun 2017 08:28:55 GMT]
      Content-Length[37]
```

As you can see, I get a "403 - forbidden". The response body is this:

```
{
    "error": "Key not authorised"
}
```

In the meantime I will try the JWT-plugin for Tyk. As I understand, the only difference for the API consumers is that they need to send the "access_token" instead of the "id_token" in their requests.

**Comment by ChristianCiach** [comment] 2017-06-28 08:46
By the way: The quickness of your responses is amazing!

**Comment by buger** [comment] 2017-06-28 09:10
So, In your policy json access rights you have, "41433797848f41a558c1573d3e55a410" which should be your API id, and inside this object you have `"api_id": "1",`. But this ID's should actually match. 

Note that dashboard was built for managing distributed configurations, so if you start new gateway process it automatically sync all your definitions. 

So it is unlikely that you can distribute your API definitions and policies via files using ansible and at the same time use dashboard. You have to pick one way. 

Also note that lot of our users who use dashboard, use only its API, and you can easily script all the actions using Dashboard API. And for example using Tyk Pump you can even send traffic to elastic search instead of mongo/dashboard.

**Comment by ChristianCiach** [comment] 2017-06-28 10:11
Thank you, it seems to work using the api-id as the access-right-key. Although, stating the api-id twice seems redundant and confusing.

I wish the logging would be clearer about the cause of the problems. When a request uses an expired id_token, tyk just logs "JWT Invalid: Validation error. Jwt token validation failed.", too. This makes debugging very hard if our customers ask as why their request to our API doesn't work.

**Comment by ChristianCiach** [comment] 2017-06-28 10:14
Also, I kind of hoped that Tyk would include some information from the id_token as additional headers to the upstream request, like the username for example. Currently the upstream service needs to parse the id_token by itself. I've hoped to avoid adding upstream logic like this by using an API gateway.

**Comment by ChristianCiach** [comment] 2017-06-28 10:16
To add to my last message: I just see that this may be already possible using dynamic request header modifications. I will investigate this...

**Comment by buger** [comment] 2017-06-28 10:27
Yeah, Tyk define 2 special meta variables which can be included into headers dynamically: `$tyk_meta.TykJWTSessionID` and `$tyk_meta.ClientID`. To make it works, just inject new header with one of the values above.

**Comment by ChristianCiach** [comment] 2017-06-28 10:35
Thank you for your help this far. I guess this ticket is solved and can be closed.

Unfortunately, neither the TykJWTSessionID nor the ClientID is useful for the downstream service. I need at least the preferred_username. I will try to figure this out.

**Comment by ChristianCiach** [comment] 2017-06-28 10:39
Your documentation says this:

> In order to make OIDC Access tokens meaningful in analytics data, Tyk will also set na ALias for the itnernal token so the user can be easily identified in analytics. The OIDC Alias will always be the ClientID + User ID provided by the IDP. This can then be queried separately by

I feel like the crucial part is missing :)

**Comment by james-tyk** [comment] 2017-06-28 10:47
Thanks @ChristianCiach - we'll look at updating that in the docs! 

Would you be able to drop me an email on James@tyk.io with a couple of details about your use-case, etc, so we can log your details and ensure we provide good service in the future?

Also, we offer a range of options for larger/commercial deployments, including licences for managing multi-gateway deployments and support SLA services. 

I'd be happy to provide details of those for your reference at the same time.

James@tyk.io

**Comment by ChristianCiach** [comment] 2017-06-28 10:50
Thanky, you will hear back from me in a few minutes.

**Comment by buger** [comment] 2017-06-28 11:35
I think what you may need is here https://tyk.io/docs/transform-traffic/request-headers/ "Injecting Context Data into Headers" section. Take a look at `$jwt_claims_CLAIMNAME`, where you should replace CLAIMNAME with actual variable you want. I know that docs says `(not OIDC Middleware)`, do not believe it 🙈 , it should work for OpenID.

We going to fix docs and improve OpenID docs.

Thank you!

**Comment by ChristianCiach** [comment] 2017-06-28 11:51
Wow, this is **exactly** what I am looking for! Using Keycloak as the IDP I am able to inject any attribute (like the username) as a claim into the id_token. I will try this right away!

**Comment by buger** [comment] 2017-06-28 12:01
😎

**Closed by buger** 2017-06-28 12:01 UTC
Labels: bug

**Comment by ChristianCiach** [comment] 2017-06-28 12:08
I can't get this to work :(

This is my api.json:

```
{
      "name": "emsys-api",
      "api_id": "1",
      "use_openid": true,
      "openid_options": {
        "providers": [
          {
            "issuer": "http://login.hub.development.ems/auth/realms/vktest",
            "client_ids": {
              "YXBpLWdhdGV3YXk=": "default"
            }
          }
	],
	"segregate_by_client": false
      },
      "version_data": {
          "not_versioned": true,
          "versions": {
              "Default": {
                 "name": "Default",
                 "use_extended_paths": true,
                 "global_headers": {
                      "X-Name": "$jwt_claims_name"
                 }
              }
          }
      },
      "proxy": {
          "listen_path": "/test-api/",
          "target_url": "http://apigate.local:10082/",
          "strip_listen_path": true
      },
      "active": true
}
```

The header reaching the service is this:
`X-Name: $jwt_claims_name`

The decoded JWT is this:
```

{
  "jti": "6b4afa91-db51-4fd8-b062-111421b39799",
  "exp": 1498646175,
  "nbf": 0,
  "iat": 1498645875,
  "iss": "http://login.hub.development.ems/auth/realms/vktest",
  "aud": "api-gateway",
  "sub": "84fdc452-cd72-46b0-8ae7-5db6b9ea82f6",
  "typ": "ID",
  "azp": "api-gateway",
  "auth_time": 0,
  "session_state": "5f6723c3-379f-4d32-9a65-ce5761fcaf24",
  "acr": "1",
  "name": "Christian Ciach",
  "preferred_username": "christianc",
  "given_name": "Christian",
  "family_name": "Ciach",
  "email": "christian.ciach@censored.de"
}
```

I will try this using the JWT auth method.

**Comment by buger** [comment] 2017-06-28 12:13
I believe it should be `$tyk_meta.jwt_claims_name`. Also, ensure that your API spec has `enable_context_vars` set to true.

**Comment by ChristianCiach** [comment] 2017-06-28 12:23
I feel so close, yet so far away...

Log says:
`time="Jun 28 14:22:18" level=warning msg="Session Meta Data not found for key in map: jwt_claims_name"`

Api def:

```
{
      "name": "emsys-api",
      "api_id": "1",
      "enable_context_vars": true,
      "use_openid": true,
      "openid_options": {
        "providers": [
          {
            "issuer": "http://login.hub.development.ems/auth/realms/vktest",
            "client_ids": {
              "YXBpLWdhdGV3YXk=": "default"
            }
          }
	],
	"segregate_by_client": false
      },
      "version_data": {
          "not_versioned": true,
          "versions": {
              "Default": {
                 "name": "Default",
                 "use_extended_paths": true,
                 "global_headers": {
                    "X-Name": "$tyk_meta.jwt_claims_name"
                 }
              }
          }
      },
      "proxy": {
          "listen_path": "/test-api/",
          "target_url": "http://apigate.local:10082/",
          "strip_listen_path": true
      },
      "active": true
}

```

**Comment by ChristianCiach** [comment] 2017-06-28 12:26
The meta_data inside Redis is just this:

```
  "meta_data": {
    "ClientID": "api-gateway",
    "TykJWTSessionID": "d5eee4348fcb63184b1baef96e6eb55f"
  },
```

I also tried to add `"enable_context_vars": true,"` to the object "version_data -> versions -> Default" inside the api definition, but no success.

**Comment by ChristianCiach** [comment] 2017-06-28 12:29
I will create a thread at https://community.tyk.io/ for this. Sorry for hijacking this github-issue so far.

Being a software developer myself, I am absolutely guilty of missing/incomplete documention myself, so you have my sympathies in this regard :) I think this discussion was fruitful for both of us this far.

**Comment by buger** [comment] 2017-06-28 12:40
Oh, I made a typo and completely confused this issue, you need to use `$tyk_context` not `$tyk_meta` variable.

**Comment by ChristianCiach** [comment] 2017-06-28 12:42
Yeah, I was this far myself (by doing RTFM), but still:

`time="Jun 28 14:37:35" level=warning msg="Context Data not found for key in map: jwt_claim_name"`

I am reading the go-code right now (I am not a go programmer, but I can read it) so I will figure this out. I will present my solution here for the poor souls finding this issue through Google.

**Comment by ChristianCiach** [comment] 2017-06-28 12:50
I am stupid: The prefix is `jwt_claims_`, not `jwt_claim_`. It's working perfectly!

This is my working api definition:


```
{
      "name": "emsys-api",
      "api_id": "1",
      "enable_context_vars": true,
      "use_openid": true,
      "openid_options": {
        "providers": [
          {
            "issuer": "http://login.hub.development.ems/auth/realms/vktest",
            "client_ids": {
              "YXBpLWdhdGV3YXk=": "default"
            }
          }
	],
	"segregate_by_client": false
      },
      "version_data": {
          "not_versioned": true,
          "versions": {
              "Default": {
                 "name": "Default",
                 "use_extended_paths": true,
                 "enable_context_vars": true,
                 "global_headers": {
                    "X-Claim-Name": "$tyk_context.jwt_claims_name"
                 }
              }
          }
      },
      "proxy": {
          "listen_path": "/test-api/",
          "target_url": "http://apigate.local:10082/",
          "strip_listen_path": true
      },
      "active": true
}
```

Now I will figure out if the JWT auth method is maybe a better match for my use cases. The auth methods seem to be very similar, but our customers may be more familiar with sending access_token instead of id_token to access APIs. One way or the other, Tyk seems to be suitable for our needs. Thank you so much for all your help!
