### ISSUE TITLE
[TT-398] Support clock skew for OIDC

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2865] opened 2020-02-04 10:44 UTC
**Is your feature request related to a problem? Please describe.**

From our docs: 
https://tyk.io/docs/tyk-rest-api/api-definition-objects/jwt/
> Due to the nature of distrusted systems it is expected that despite best efforts you can end up in a situation with clock skew between the issuing party (An OpenID/OAuth provider) and the validating party (Tyk).
> 
> This means that in certain circumstances Tyk would reject requests to an API endpoint secured with JWT with the "Token is not valid yet" error . This occurs due to the clock on the Tyk server being behind the clock on the Identity Provider server even with all servers ntp sync'd from the same ntp server.

**Describe the solution you'd like**
Add the same support we have for generic JWT auth method.

**Describe alternatives you've considered**

Might be possible to use generic jwt auth method instead but it makes it non-trivial choice for users

**Additional context**

**Comment by wclaeys** [comment] 2020-02-14 09:28
Actual code checking this is found here:
https://github.com/dgrijalva/jwt-go/blob/master/claims.go

**Comment by buger** [comment] 2020-02-14 09:44
Yeah and we use it in jwt middleware. The issue is that openid library we use does not expose this option yet

**Comment by christtyk** [comment] 2020-08-05 14:24
Reopen

**Comment by letzya** [comment] 2020-11-24 15:38
https://tyktech.atlassian.net/browse/TT-398

**Comment by andyo-tyk** [comment] 2023-03-09 16:46
Sorry, we won't be adding this to Tyk - we are not looking to extend the OIDC Authentication support at this tie.

**Closed by andyo-tyk** 2023-03-09 16:46 UTC
Labels: enhancement, wontfix
