### ISSUE TITLE
Http signature spec compliance

### ISSUE THREAD

**Issue by Randita** [TykTechnologies/tyk#199] opened 2016-02-18 10:30 UTC
Hello, we've noticed that in your implementation of HMAC signature (based on the [http signatures spec](https://web-payments.org/specs/ED/http-signatures/2014-02-01/#section-2.1)), you only support the default date header. 

There is no way to sign the request with extra headers parameters as described by the spec.

Do you plan on adding support for the optional headers ?

**Comment by lonelycode** [comment] 2016-02-18 10:33
Yes, eventually. This has been raised elsewhere. It isn't a priority at the moment, but we're always open to pull requests :-)

**Comment by Randita** [comment] 2016-02-18 10:36
Ok, thanks for the reply ! We'll give it a shot :)

**Comment by nvuppala** [comment] 2016-02-18 16:40
We do also need to support optional headers for hmac,

**Comment by lonelycode** [comment] 2016-02-22 13:16
Duplicate of #118 which has been fixed in develop branch.

**Closed by lonelycode** 2016-02-22 13:16 UTC
