### ISSUE TITLE
[TD-932 ] - Bad version number on go build

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3043] opened 2020-04-22 20:27 UTC
When you checkout a specific tag like `v2.9.4` and run `go build`, the result reports `--version` as 2.10 instead.

Also, the Redis version-check-gateway key is missing at runtime when tyk is built from source with `go build`.

Please amend the build steps so that development versions report accurate version information.

For example, just print gateway.VERSION on `--version`.

Perhaps append a `-dev` suffix in master, if you like.

**Comment by alephnull** [comment] 2022-04-21 15:00
The [current automation](https://github.com/TykTechnologies/tyk/blob/master/ci/goreleaser/goreleaser.yml#L22) sets this appropriately and has been in effect since 4.0. 

>  the Redis version-check-gateway key is missing at runtime when tyk is built from source with go build.
I'm not sure I understand the problem, would you explain it a bit more, or cite some documentation as to what is expected here?

**Comment by andyo-tyk** [comment] 2023-02-27 11:05
Hi,

I will close this issue, as it seems the issue no longer exists.

Please don't hesitate to open another ticket if the issue is still reproducible in latest Tyk.

Thanks for your contribution to Tyk!

**Closed by andyo-tyk** 2023-02-27 11:05 UTC
Labels: bug, zendesk
