### ISSUE TITLE
Tyk attempts to open thousands connections to Redis machine on failure

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#520] opened 2017-02-15 14:26 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If for some reason there are problems with connections to Redis (for example master failed), Redis attempts to make thousands of connections to Redis server.

**What is the expected behavior?**
There should not be a significant increase of connection attempts; it should gracefully retry requests to Redis using some interval. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
We have no clear way to replicate the issue, but worth trying stopping Redis server after the connection was initialized, and making few requests.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

This behavior can be related to the following code https://github.com/TykTechnologies/tyk/blob/master/redis_cluster_handler.go#L136
If key is not found it tries to connect in loop.

**Comment by mvdan** [comment] 2017-02-15 14:37
I looked at this last week for a somewhat related issue - a race. Calls to `Connect` are not controlled at all, so the code is racy.

I did not post a fix because the obvious fix of adding a mutex of some sort could be tricky - it could lead to `GetKey` blocking all the time or for really long amounts of time.

A change that would fix this bug but not the race would be simpler - we would have to limit the retries to a limited amount (three, for example) and have it wait between attempts. Note that it would still be really racy, but it can't be worse than what it is now. In fact the chances of races would probably be lower since there would be fewer reconnection attempts.

@buger @lonelycode thoughts on this fix to backport to 2.3? The race fix likely doesn't need backporting.

**Comment by buger** [comment] 2017-02-15 14:38
Race itself not, but actually fixing related endless connection loop should be included into 2.3.

**Comment by mvdan** [comment] 2017-02-15 14:39
Okay, will have a PR soon.

**Comment by mvdan** [comment] 2017-02-15 15:41
I've tried to reproduce this with a test using a tcp server, but no luck. Basically, the singletons are only ever set to non-nil pointers, so the logic that fires the reconnects (`GetRelevantClusterReference(r.IsCache) == nil`) will never be true as soon as we've set up the cluster for the first time.

We set either of the singleton pointers to this:

```
cluster := rediscluster.NewRedisCluster(seed_redii, poolConf, false)
return &cluster
```

`rediscluster` never errors when creating the cluster, as it does the actual connections in the background.

So I don't think our reconnect code is the cause for all those connections. It could be `rediscluster` internally trying to open more connections, but then it would be a bug in its reconnect code, not ours.

@lonelycode thoughts?

**Comment by lonelycode** [comment] 2017-02-16 09:48
All redigocluster driver does is add some handlers to manage cluster slots handling and re-sharding, under the hood, it actually creates many redigo redis clients (one for each cluster seed_redii entry), it's just a wrapper with bells on.

Also, redigocluster is badly maintained, which is why we have internalised it - I wouldn't trust upstream too much, the original code had serious problems with parallelism. So we live with it until we swap out for a newer overall driver.

In fact, a long-term goal should be to swap out to a new driver.

The customer that reported this bug was using the healthcheck API under load, which is a terrible thing to do because it calls to redis on *every* request to increment counters, it is a legacy feature that we no longer recommend anyone use, but they insisted. 

What will happen in this scenario is: each request comes in, if redis fails, the request will try to write to healthcheck, fail, and call itself, and fail, but this will back-up across all the http handler go routines and so just stack up and try to open thousands of connections because that's what's happening at the HTTP end with each request because of the load test.

So load was generating the connections, not the redis driver IMO.

I think the failure tail calls in most of the methods are ok, because they won't fail instantly, they fail after timeout (unreachable network / connection refused etc.) so it's a slow growth and not necessarily the root cause.

They are still awful and must be handled better.

**Comment by buger** [comment] 2017-02-20 10:25
We need to check distributed rate limiter and pubsub as well

**Comment by mvdan** [comment] 2017-02-21 10:19
Regarding pub/sub, our current code was broken somewhat. See https://github.com/TykTechnologies/tyk/pull/544/commits/a1fb2db6b694bdb8d3ce3ccaecd0f9e3bcd6cef8. Perhaps related.

**Comment by mvdan** [comment] 2017-02-28 16:48
Potential fix shipped in 2.3.3 and released, moving to 2.3.4 in case we have any more info or we're able to reproduce.

**Comment by mvdan** [comment] 2017-03-15 18:33
Another potential bugfix in 2.3.4. Kicking forward to 2.4, where we'll hopefully replace the buggy rediscluster library.

**Comment by mvdan** [comment] 2017-08-23 15:35
Not replacing just yet, and this hasn't been an issue as of late. Moving to 2.5.

**Closed** 2020-04-25 03:34 UTC
Labels: bug, wontfix
