### ISSUE TITLE
Memory Leak in RPC mode

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#366] opened 2017-01-17 09:39 UTC
Users have reported a bug that causes memory leaks when Tyk is running in RPC mode. Affected users have reported needing to restart the Tyk Gateway service as a workaround.

**Comment by buger** [comment] 2017-01-25 13:03
I were able to reproduce it, and pinpoint to some specific functionality, but did not fix yet.

Movin this task 2.4 milestone.

![image](https://cloud.githubusercontent.com/assets/14009/22291488/ac80b5a8-e317-11e6-8ed9-b3790d621f36.png)

So, it leaks somewhere in the gorpc package, when our analytics turned on.
When analytics turned off, it reaches some local memory maximum and does not grow further.

**Comment by lonelycode** [comment] 2017-01-25 13:51
It might not be gorpc but instead how the analytics purger works with the RPC client, there's two Connect functions:

`RPCStorageHandler` uses this: 

https://github.com/TykTechnologies/tyk/blob/master/rpc_storage_handler.go#L151

While the `RPCPurger` uses this: 

https://github.com/TykTechnologies/tyk/blob/master/rpc_analytics_purger.go#L34

I wonder if it's because it is assigning an internal reference to the object (`Store`) instead of just referencing the RPC singleton directly.

**Comment by mvdan** [comment] 2017-01-27 15:30
Not sure if this is it (found this weird code randomly), but this is definitely wrong and a leak:

```
func (r RPCPurger) StartPurgeLoop(nextCount int) {
       time.Sleep(time.Duration(nextCount) * time.Second)
       r.PurgeCache()
       r.StartPurgeLoop(nextCount)
}
```

The calls will stack up ad infinitum. Given the 10 seconds, it would probably take a long time (weeks?) for Go to actually crash becuase of the stack being too large. Until then, the stack just keeps on growing, hence, memory leak.

I'll post a PR soon. @buger please re-run your tests once it's merged.

**Comment by lonelycode** [comment] 2017-01-30 12:16
This could very likely be the cause for this issue - I'd like to get this into the 2.3.2 bugfix release.

**Comment by mvdan** [comment] 2017-01-30 21:34
I was not given the chance to update the commit message, so closing manually.

**Closed by mvdan** 2017-01-30 21:34 UTC
Labels: bug
