### ISSUE TITLE
[TT-9365] Enforced timeout should be a positive number

### ISSUE THREAD

**Issue by SDkie** [TykTechnologies/tyk#4857] opened 2023-03-13 09:37 UTC
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: Self Managed

**Describe the bug**
Tyk-dashboard is allowing me to set a negative enforced timeout. This issue should be added in the tyk-dashboard, but I guess tyk-dashboard is not open source so I am creating the issue here.  Feel free to close it if it's not required.

**Reproduction steps**

1. Add api
2. Add endpoint with negative Enforced timeout

**Actual behavior**
I am able to set negative Enforced timeout

**Expected behavior**
Enforced timeout should be a positive number

**Screenshots/Video**
<img width="1175" alt="Screenshot 2023-03-13 at 2 05 25 PM" src="https://user-images.githubusercontent.com/1321321/224661502-6ceff310-1583-4742-9e80-d7db8a830b01.png">

**Comment by andyo-tyk** [comment] 2023-07-05 16:09
Thanks for raising this issue @SDkie - it looks like a bug, we'll investigate.

**Comment by andyo-tyk** [comment] 2023-08-17 14:57
Hi @SDkie,

I can confirm we're working on including a fix for this in an upcoming patch.
I'll confirm the fix version when I have it.

Thanks again for supporting Tyk!

**Closed** 2023-08-21 17:06 UTC
Labels: bug, manage-squad
