### ISSUE TITLE
Unable to send grpc messages larger than 4mb after increasing grpc.MaxRecvMsgSize

### ISSUE THREAD

**Issue by Janrain-Stephanie** [TykTechnologies/tyk#2295] opened 2019-05-20 18:20 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Cannot send grpc messsages larger than 4mb after message size increase 

**What is the expected behavior?**
Able to send message larger than 4mb to grpc service

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Step 1: Configure tyk to use grpc
```json
"coprocess_options": {
    "enable_coprocess": true,
    "coprocess_grpc_server": "tcp://127.0.0.1:5000"
  }
```

Step 2: Create a grpc middleware service that has a message size greater than 4 mb
```go
import (
	"net"
	"net/http"

	"github.com/janrain/grpc-service/dispatcher"

	"github.com/TykTechnologies/logrus"
	"github.com/TykTechnologies/tyk/coprocess"
	logger "github.com/TykTechnologies/tykcommon-logger"
	"google.golang.org/grpc"
)

const (
	//ListenAddress port
	ListenAddress = "localhost:5000"
	//ManifestAddress port
	ManifestAddress = ":8888"
	//MaxMsgSize for file = 100MB
	MaxMsgSize = 1024 * 1024 * 100
)

//ArtifactVersion is the variable that holds the version
var ArtifactVersion string
var log = logger.GetLogger()
var mainPrefix = "main"

func main() {
	log.WithFields(logrus.Fields{
		"prefix": mainPrefix,
	}).Info("## Artifact Version: ", ArtifactVersion, " ##")

	lis, err := net.Listen("tcp", ListenAddress)
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}
	log.Printf("Starting grpc server on %v", ListenAddress)
	grpcServer := grpc.NewServer(grpc.MaxRecvMsgSize(MaxMsgSize))
	coprocess.RegisterDispatcherServer(grpcServer, &dispatcher.Dispatcher{})
	go grpcServer.Serve(lis)

	log.Fatal(http.ListenAndServe(ManifestAddress, nil))
}
```

Step 3: Send a payload larger than 4mb
```
time="May 15 23:11:21" level=error msg="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9321827 vs. 4194304)"
```

Interestingly if you go over the services set message size, you will get a max message error:
```
time="May 20 18:10:05" level=error msg=rpc error: code = ResourceExhausted desc = grpc: received message larger than max (207618711 vs. 104857600)"
```
When messages fall below the set size you see:
```
time="May 20 18:11:10" level=error msg="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (83886792 vs. 4194304)"
```

We tracked the error messages to be one from the client and one from the server

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8, worked in 2.7.7

**Comment by matiasinsaurralde** [comment] 2019-05-20 18:28
Hi, we have created a fix for this #2204 
We're planning to incorporate this soon

**Comment by furkansenharputlu** [comment] 2019-12-30 07:51
The PR is merged so I am closing this issue. Also, duplicate of https://github.com/TykTechnologies/tyk/issues/2203

**Closed by furkansenharputlu** 2019-12-30 07:51 UTC

**Comment by Janrain-Stephanie** [comment] 2020-01-21 19:08
Hi, do you have an ETA on when this will be released?

**Comment by buger** [comment] 2020-01-21 19:53
@Janrain-Stephanie next week.
