### ISSUE TITLE
Token isn't updated if Policy Partitions are false

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1559] opened 2018-03-22 14:15 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When Policy Partitions are false, gateway will not update token after we made changes on policy
**What is the expected behavior?**
When Policy Partitions are false, gateway should update token after we made changes on policy
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create policy with api1 and api2
2. Create token per that policy
3. Create api3 and add api3 to policy
4. Trigger a request to gateway with token

Actual:
We will got 403 error since access rights are not applied on token
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.5.3 and 2.5.2

**Comment by buger** [comment] 2018-03-22 19:21
The current way to mitigate the issue is to check all three partition checkboxes.

**Comment by buger** [comment] 2018-03-23 14:17
Should be fixed

**Closed** 2018-03-23 14:17 UTC
Labels: bug
