### ISSUE TITLE
Gateway not reporting jaeger spans

### ISSUE THREAD

**Issue by tomshy** [TykTechnologies/tyk#3578] opened 2021-06-03 15:04 UTC
**Version**
- Version: 3.0.0+
- Environment: On prem

**Describe the bug**
Tyk gateway  report jaeger spans

**Reproduction steps**

1. Add api... 
2. Set up jaeger server 
3. Follow this [configuration](https://tyk.io/docs/advanced-configuration/distributed-tracing/jaeger/)

**Actual behavior**
Nothing happens or logged.

**Expected behavior**
The gateway should log trace information.

**Logs (debug mode or log file):**
Nothing on logs as seen in version 2.9.4

**Comment by n2linux** [comment] 2021-06-03 16:46
Duplicate of #3338

**Comment by n2linux** [comment] 2021-06-03 16:48
@tomshy Thanks for opening this! We've fixed this issue in #3418 and this should be made available once we release Tyk v3.0.7/v.3.2.2/v4.0.

**Closed by n2linux** 2021-06-03 16:48 UTC
Labels: bug
