### ISSUE TITLE
Updating key, errors on master branch

### ISSUE THREAD

**Issue by lghiur** [TykTechnologies/tyk#1050] opened 2017-08-30 07:49 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to update a key from Dashboard, I get the following error:

Gateway: 
```
ERROR api: Could not add key for this API ID, API doesn't exist. api_id=e2b7e190866145fd42fcd053fd0d3f16 key=5989653286341f6a160639cfb8960814d0f448789fc05bebafaad593 org_id=5989653286341f6a160639cf path=-- server_name=system user_id=system user_ip=--
```

Analytics:
```
ERROR API Request failed: {"status":"error","message":"Failed to create key, ensure security settings are correct."}

[Aug 30 10:44:20] ERROR Failed to update session object to Tyk
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Go to the Dashboard and create a new key;
2. Try to update the key you just created with new data

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by mvdan** [comment] 2017-08-30 07:52
(this works fine on stable)

**Comment by mvdan** [comment] 2017-08-31 14:16
This is indeed a gateway regression of some sort. The underlying issue was that on stable, if we failed to update a key, we silently returned 200, while on master, we return a 500.

stable:

```
addUpdateErr := doAddOrUpdate(keyName, newSession, suppress_reset)
if addUpdateErr != nil {
        success = false
        responseMessage = createError("Failed to create key, ensure security settings are correct.")
}
```

(note how `code` isn't set, so it remains at the default `200`; `success = false` doesn't set the code either)

master:

```
if err := doAddOrUpdate(keyName, &newSession, suppressReset); err != nil {
        return apiError("Failed to create key, ensure security settings are correct."), 500
}
```

To make this more obvious, the actual cause of the error is seen on both stable and master:

```
ERROR api: Could not add key for this API ID, API doesn't exist. api_id=22ad7a2b8b194ba374a389e1e3682c95 key=638fdf169f7342f140612b7b6b01b99a org_id= path=-- server_name=system user_id=system user_ip=--
```

What causes the error is that the key is attached to an ApiID that isn't known by the gateway, i.e. that isn't in the global `apisByID` map. I'm not exactly sure why this would happen. Perhaps because the Dashboard stores the api definitions on its own and the gateway doesn't have them?

Either way, this seems like lousy coding in stable that we fixed in master without realising. And it seems to me like the error is real and should not be ignored. @buger thoughts?

**Comment by lonelycode** [comment] 2017-08-31 19:30
So the dashboard does store API Definitions, but it is not guaranteed that the API Definition is on the gateway (for example if it is a "sharded" gateway that uses tags), OR if a gateway ignored an API Definition because of a dupe (used to happen) then this shyould happen.,

Basically, the gateway refuses to put API Definitions into the store unless it can find all the API IDs in the ACL in it's own map.

It could be a few things:

- The wrong ID is being added to the ACL (Dashboard has an internal ID and *also* an API ID, we must use the API ID for all ACL actions, same goes with policies).
- An empty ACL entry is being added to the ACL (i.e. a `{}` object)

What we need to see the actual object the dashboard UI is sending on update. It could just be data corruption.

I don;t have this version running a the moment, so @lghiur if you can share the Session Object from when  you CREATE the key and also from when you UPDATE the key, we might know more.

**Comment by lghiur** [comment] 2017-09-01 05:16
@lonelycode I would like to add that this bug is reproducible on master branch of tyk-analytics-ui (current version of the code on stable too). Here is the object that is being sent on PUT request:

`{
	"last_check": 0,
	"allowance": 1000,
	"rate": 1000,
	"per": 60,
	"expires": 1504246367,
	"quota_max": -1,
	"quota_renews": 1506834795,
	"quota_remaining": -1,
	"quota_renewal_rate": 2592000,
	"access_rights": {
		"01ff8eb249634fe06f8eb710425d158a": {
			"api_name": "new api",
			"api_id": "01ff8eb249634fe06f8eb710425d158a",
			"versions": ["Default"],
			"allowed_urls": null
		}
	},
	"org_id": "59a6adbd86341f0485c93507",
	"oauth_client_id": "",
	"basic_auth_data": {
		"password": "",
		"hash_type": ""
	},
	"jwt_data": {
		"secret": ""
	},
	"hmac_enabled": false,
	"hmac_string": "",
	"is_inactive": false,
	"apply_policy_id": "",
	"data_expires": 0,
	"monitor": {
		"trigger_limits": null
	},
	"meta_data": {},
	"tags": [],
	"alias": "",
	"last_updated": "1504242778"
}`

**Comment by ilijabojanovic** [comment] 2017-09-04 09:42
@mvdan I have similar or maybe related issue with this task.
Issue is visible only over dashboard api not visible on UI.

Gateway branch: Master
Dashboard branch: Refactoring
Version: On-prem

Reproduction steps:
1. Create token protected api over dashboard api
2. Create key request for that api over api and trigger request 

Actual:
Dashboard api returns this response:
```
{"Status":"Error","Message":"Failed to save new session object to Tyk: Failed to create key: Post http://tyk-gateway:8181/tyk/keys/create: EOF","Meta":null}
```
In gateway console we have this:
```
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Inbound redis event received" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Inbound redis event received" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Reloading endpoints" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Reload queued" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Initiating reload" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Loading policies" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Using Policies from Dashboard Service" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Mutex lock acquired... calling" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Calling dashboard service for policy list" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Loading Policies Finished: Nonce Set: NDJmMmYwMjctNTc2Zi00NzY4LTUwZDktYTUzZmRlNWUyOTRiMTI5ZjJkOTI1NTQ1NDMxNjUyODk2YzEzYTk2OThmZjI=" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Processing policy list" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Calling: http://tyk-dashboard:3000/system/apis" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Using: NodeID: 42f2f027-576f-4768-50d9-a53fde5e294b" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=info msg="Reset quota for key." inbound-key="****c335" key=quota-bb69b66e 
[36mtyk-gateway_1    |[0m 2017/09/02 16:17:07 http: panic serving 172.18.0.6:50938: runtime error: invalid memory address or nil pointer dereference
[36mtyk-gateway_1    |[0m goroutine 755 [running]:
[36mtyk-gateway_1    |[0m net/http.(*conn).serve.func1(0xc42050c640)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1721 +0xd0
[36mtyk-gateway_1    |[0m panic(0xc864c0, 0x131fd30)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
[36mtyk-gateway_1    |[0m main.(*DefaultSessionManager).ResetQuota(0x13467d0, 0xc4205e8e00, 0x38, 0xc42070adc0)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:101 +0x471
[36mtyk-gateway_1    |[0m main.createKeyHandler(0x126e760, 0xc42025c380, 0xc4204e4800)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/api.go:925 +0x29dc
[36mtyk-gateway_1    |[0m main.allowMethods.func1(0x126e760, 0xc42025c380, 0xc4204e4800)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/api.go:62 +0x172
[36mtyk-gateway_1    |[0m net/http.HandlerFunc.ServeHTTP(0xc4204fe060, 0x126e760, 0xc42025c380, 0xc4204e4800)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
[36mtyk-gateway_1    |[0m github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420288050, 0x126e760, 0xc42025c380, 0xc4204e4800)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
[36mtyk-gateway_1    |[0m main.InstrumentationMW.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/instrumentation_handlers.go:51 +0xab
[36mtyk-gateway_1    |[0m net/http.HandlerFunc.ServeHTTP(0xc4204d9900, 0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
[36mtyk-gateway_1    |[0m main.checkIsAPIOwner.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/main.go:345 +0x1ef
[36mtyk-gateway_1    |[0m net/http.HandlerFunc.ServeHTTP(0xc4204d9920, 0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
[36mtyk-gateway_1    |[0m net/http.StripPrefix.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1977 +0xcf
[36mtyk-gateway_1    |[0m net/http.HandlerFunc.ServeHTTP(0xc4204d7800, 0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
[36mtyk-gateway_1    |[0m github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420228c80, 0x126e760, 0xc42025c380, 0xc4204e4600)
[36mtyk-gateway_1    |[0m 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
[36mtyk-gateway_1    |[0m net/http.(*ServeMux).ServeHTTP(0xc4202eb440, 0x126e760, 0xc42025c380, 0xc4204e4400)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:2238 +0x130
[36mtyk-gateway_1    |[0m net/http.serverHandler.ServeHTTP(0xc4201ec630, 0x126e760, 0xc42025c380, 0xc4204e4400)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:2568 +0x92
[36mtyk-gateway_1    |[0m net/http.(*conn).serve(0xc42050c640, 0x126f560, 0xc4205e8ac0)
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:1825 +0x612
[36mtyk-gateway_1    |[0m created by net/http.(*Server).Serve
[36mtyk-gateway_1    |[0m 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="INITIALISING EVENT HANDLERS" 
[36mtyk-gateway_1    |[0m time="Sep  2 16:17:07" level=debug msg="Checking for transform paths..." 
```

**Comment by mvdan** [comment] 2017-09-04 09:44
This is a separate issue - please file a new issue in this repo.

**Comment by ilijabojanovic** [comment] 2017-09-04 10:04
@mvdan Done
https://github.com/TykTechnologies/tyk/issues/1063

**Comment by mvdan** [comment] 2017-09-06 14:36
This was a configuration issue; master isn't broken.

**Closed by mvdan** 2017-09-06 14:36 UTC
Labels: bug
