### ISSUE TITLE
Double response from auth go plugin

### ISSUE THREAD

**Issue by rostyslavkhaniukov** [TykTechnologies/tyk#5572] opened 2023-09-29 15:08 UTC
**Branch/Environment/Version**
- v5.2.0
- OSS edition

**Describe the bug**
When I try to send a custom response from the auth plugin like this:
```go
func AuthCheck(rw http.ResponseWriter, r *http.Request) {
	token := r.Header.Get("Authorization")
	if token != "d3fd1a57-94ce-4a36-9dfe-679a8f493b49" && token != "3be61aa4-2490-4637-93b9-105001aa88a5" {
		rw.WriteHeader(http.StatusUnauthorized)

		replyData := map[string]interface{}{
			"current_time": time.Now(),
		}

		jsonData, err := json.Marshal(replyData)
		if err != nil {
			rw.WriteHeader(http.StatusInternalServerError)
			return
		}

		rw.Write(jsonData)
		return
	}
       ...
```
I get a broken response like
```json
{"current_time":"2023-09-29T14:34:11.024928287Z"}{
    "error": "plugin function sent error response code: 401"
}
```
But I don't need this hardcoded error `plugin function sent error response code...`.

**Actual behavior**
Broken double response

**Expected behavior**
Custom response overrides default response

**Comment by andyo-tyk** [comment] 2023-10-05 13:32
Hi @rostyslavkhaniukov,

Thanks for raising this - the good news is that we have a fix coming soon (in Tyk 5.0.7 / 5.2.2).

Thanks for supporting Tyk!

<duplicate of https://github.com/TykTechnologies/tyk/issues/5141>

**Closed by andyo-tyk** 2023-10-05 13:32 UTC
Labels: bug
