### ISSUE TITLE
UrlRewriter & tyk_context.headers_* works in 2.6.4 but not 2.7.6

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#2143] opened 2019-02-27 18:33 UTC
This is failing w/ Tyk 2.7.6 hybrid, it works fine w/ Tyk 2.6.4 hybrid

Note my API def's target url is set to `https://nothing.fqdn.that.wontbe.used:8888/`

In JSVM middleware I set a header like:

`X-My-Proxytourl=https://someotherhost:8888/some/path`

Rewrite config:

```json
"url_rewrites": [
      {
          "path": "/my/\\d.\\d/api/token",
          "method": "GET",
          "match_pattern": "/my/\\d.\\d/api/token",
          "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
          "triggers": [],
          "MatchRegexp": null
      },
      {
          "path": "/my/\\d.\\d/api/token",
          "method": "POST",
          "match_pattern": "/my/\\d.\\d/api/token",
          "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
          "triggers": [],
          "MatchRegexp": null
      }
  ]
```

Via curl or anything I make a request like `GET https://my-tyk-gw/my/1.1/api/token`

My JSVM plugin properly sets the HTTP request header: 

`X-My-Proxytourl: https://someotherhost:8888/some/path`

The request fails with the following error in the logs

```
http: proxy error: dial tcp: lookup nothing.fqdn.that.wontbe.used on 127.0.0.11:53: no such host" api_id=xxxxx org_id=xxxxx server_name=nothing.fqdn.that.wontbe.used user_id=-- user_ip="10.255.6.220, 10.0.0.72" user_name= 
```

This works fine in Tyk 2.6.4.  In Tyk 2.6.4, the UrlRewriter proxies successfully to https://someotherhost:8888/some/path 

It appears the rewriter w/ the `$tyk_context.headers_*` no longer works in 2.7.x?

I am running into this issue during testing of Tyk 2.7.6 for a planned upgrade.

**Comment by furkansenharputlu** [comment] 2019-02-28 14:05
Hi, I tested `$tyk_context.headers_*` with `2.7.6`, it seems working. Maybe header isn't set properly in JSVM. Can you please run your gateway in debug mode, make the request and share logs above of the error you mentioned. It should be something like the following:
```
[Feb 28 16:59:01] DEBUG Stripping: /normal/
[Feb 28 16:59:01] DEBUG Upstream Path is: furkan.com
[Feb 28 16:59:01] DEBUG UPSTREAM REQUEST URL: furkan.com
[Feb 28 16:59:01] DEBUG Outbound Request: https://nothing.fqdn.that.wontbe.used:8888/furkan.com
[Feb 28 16:59:01] ERROR proxy: http: proxy error: dial tcp: lookup nothing.fqdn.that.wontbe.used: no such host api_id=8c88f72eba8648cd5baddf669d090f76 org_id=5c75441ebca82a045c7dcb98 server_name=nothing.fqdn.that.wontbe.used:8888 user_id=-- user_ip=127.0.0.1 user_name=```

**Comment by bitsofinfo** [comment] 2019-02-28 14:48
I'll turn on debug logging, however my point is this was a drop-in gateway upgrade. Nothing else changed. 2.7.6 fails, 2.6.4 works

**Comment by furkansenharputlu** [comment] 2019-02-28 14:54
I want to understand whether the problem is because of JSVM or `tyk_context.headers_*`. Maybe something is broken in JSVM in 2.7.6.

**Comment by bitsofinfo** [comment] 2019-02-28 16:24
```
time="Feb 28 16:13:10" level=debug msg="Running: common"
.....
time="Feb 28 16:13:10" level=debug msg="JSVM middleware execution took: (ns) 3627083"
time="Feb 28 16:13:10" level=debug msg="Running: hostEval"
.....
time="Feb 28 16:13:10" level=info msg="hostEval 2019-2-28-16-13-10-691-20319 - traceid: none - https://my-tyk-gw/my/1.1/api/token - setting request.header: X-My-Proxytourl: https://someotherhost:8888/some/path" type=log-msg
time="Feb 28 16:13:10" level=debug msg="JSVM middleware execution took: (ns) 3695384"
time="Feb 28 16:13:10" level=debug msg="Started proxy"
time="Feb 28 16:13:10" level=debug msg="Stripping: /my/1.1/api/token"
time="Feb 28 16:13:10" level=debug msg="Upstream Path is: "
time="Feb 28 16:13:10" level=debug msg="UPSTREAM REQUEST URL: "
time="Feb 28 16:13:10" level=debug msg="Outbound Request: https://nothing.fqdn.that.wontbe.used:8888"
time="Feb 28 16:13:10" level=debug msg="Received DRL data: {xxxx solo-xxxx-8c53-4bbe-a400-xxxx 1 0 }"
time="Feb 28 16:13:10" level=debug msg="[Active Nodes]: 15 [Token Bucket Value]: 1100 [Current Load p/s]: 2 [Current Load]: 0.000000"
time="Feb 28 16:13:10" level=debug msg="Received DRL data: {xxxxx solo-xxxx-e9b4-4e5a-9dc8-xxxx 1 0 }"
time="Feb 28 16:13:10" level=debug msg="[Active Nodes]: 13 [Token Bucket Value]: 1100 [Current Load p/s]: 2 [Current Load]: 0.000000"
time="Feb 28 16:13:10" level=debug msg="Received DRL data: {xxxx solo-xxxx-4e29-4de8-93b0-xxxx 1 0 }"
time="Feb 28 16:13:10" level=debug msg="[Active Nodes]: 12 [Token Bucket Value]: 1100 [Current Load p/s]: 2 [Current Load]: 0.000000"
time="Feb 28 16:13:10" level=error msg="http: proxy error: dial tcp: lookup nothing.fqdn.that.wontbe.used:8888 on 127.0.0.11:53: no such host" api_id=xxxx org_id=xxxx server_name=nothing.fqdn.that.wontbe.used:8888 user_id=-- user_ip="10.255.6.220, 10.0.0.72" user_name=
time="Feb 28 16:13:10" level=debug msg="Sending notification{gateway-log {\"api_id\":\"xxxxx\",\"level\":\"error\",\"msg\":\"http: proxy error: dial tcp: lookup nothing.fqdn.that.wontbe.used:8888 on 127.0.0.11:53: no such host\",\"org_id\":\"xxxxx\",\"prefix\":\"proxy\",\"server_name\":\"nothing.fqdn.that.wontbe.used:8888\",\"time\":\"2019-02-28T16:13:10Z\",\"user_id\":\"--\",\"user_ip\":\"10.255.6.220, 10.0.0.72\",\"user_name\":\"\"}\n xxxxx 2019-02-28 16:13:10.919439072 +0000 UTC m=+447.323603042}"
time="Feb 28 16:13:10" level=debug msg="ISO Code: "
```

**Comment by bitsofinfo** [comment] 2019-02-28 16:28
applying headers runs through a function like this (works fine w/ tyk 2.6.4)

```
function applyRequestHeaders(request,headersToApply,headersToDelete) {

	var updatedHeaders = {};

	if (request && request.Headers) {
		for (var headerName in request.Headers) {
			var rawHeaderArrVal = request.Headers[headerName];
			if (rawHeaderArrVal && rawHeaderArrVal.length > 0) {
				updatedHeaders[headerName] = (rawHeaderArrVal[0].trim());
			}
		}
	}

	if (request && request.SetHeaders) {
		for (var headerName in request.SetHeaders) {
			var rawHeaderVal = request.SetHeaders[headerName];
			updatedHeaders[headerName] = rawHeaderVal;
		}
	}

	if (headersToApply && headersToApply != null) {
		for (var headerName in headersToApply) {
			updatedHeaders[headerName] = headersToApply[headerName].trim();
		}
	}

	if (headersToDelete && headersToDelete != null) {
		for (var headerName in headersToDelete) {
			delete updatedHeaders[headerName];
			request.DeleteHeaders = [ headerName ]
		}
	}

	// Note this is telling Tyk KV pairs to set on the Headers field
	// if it exists and not in this list it will remain.
	request.SetHeaders = updatedHeaders;
}
```

called like:
```
...

applyRequestHeaders(request,JSON.parse("{\"" +headerName1 +"\":\""+ header1value.trim() + "\"," +
                                        "\"" +headerName2  +"\":\""+ header2value.trim()   + "\"," +
                                        "\"" +proxyToUrlHeaderName +"\":\""+ proxy_to_url.trim()   + "\"}"));

...
```

**Comment by furkansenharputlu** [comment] 2019-03-01 08:58
I tested with js plugin too it worked in my local. Here is my `sampleMiddleware.js`:
```
// Create your middleware object
var sampleMiddleware = new TykJS.TykMiddleware.NewMiddleware({});

// Initialise it with your functionality by passing a closure that accepts two objects
// into the NewProcessRequest() function:
sampleMiddleware.NewProcessRequest(function (request, session, spec) {

   var updatedHeaders = {};
   updatedHeaders["X-My-Proxytourl"] = "https://www.youtube.com";
   request.SetHeaders = updatedHeaders;

    return sampleMiddleware.ReturnData(request, session.meta_data);
});
```

url_rewrites:
```
"url_rewrites": [
              {
                "path": "/my/\\d.\\d/api/token",
                "method": "GET",
                "match_pattern": "/my/\\d.\\d/api/token",
                "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                "triggers": [],
                "MatchRegexp": null
              }
```


In your logs, `time="Feb 28 16:13:10" level=debug msg="UPSTREAM REQUEST URL: "` means context variable reads the header as empty. 

Can you please check what `console.log(request.SetHeaders["X-My-Proxytourl"]);` prints before `ReturnData` and share the result in logs?

Also, if you can share the values while you are calling `applyRequestHeaders` I can try your exact scenario.

**Comment by bitsofinfo** [comment] 2019-03-01 16:12
@furkansenharputlu did you try setting the headers via that function?

**Comment by bitsofinfo** [comment] 2019-03-01 17:24
So I've noticed that some of our other APIs that use this same plugin/urlrewrite mechanism work on 2.7.6

After looking into the differences I've narrowed it down to this:

If the API def defines its whitelist/urlrewrites like this, things work fine in 2.7.6 (JSVM header is set/proxies to backend OK:

```
                    "url_rewrites": [
                        {
                            "path": "/.*",
                            "method": "GET",
                            "match_pattern": "/.*",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        },
                        {
                            "path": "/.*",
                            "method": "POST",
                            "match_pattern": "/.*",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        }
                    ]
```

If the API def defines its whitelist/urlrewrites like this, things work fail in 2.7.6 (header is still set is JSVM but its gone by the time tyk does the urlrewrite:

```
                    "url_rewrites": [
                        {
                            "path": "/my/\\d.\\d/api/token",
                            "method": "GET",
                            "match_pattern": "/my/\\d.\\d/api/token",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        },
                        {
                            "path": "/my/\\d.\\d/api/token",
                            "method": "POST",
                            "match_pattern": "/my/\\d.\\d/api/token",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        }
                    ]
```

This also fails:

```
                    "url_rewrites": [
                        {
                            "path": "/my/1.0/api/token",
                            "method": "GET",
                            "match_pattern": "/my/\\d.\\d/api/token",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        },
                        {
                            "path": "/my/1.0/api/token",
                            "method": "POST",
                            "match_pattern": "/my/\\d.\\d/api/token",
                            "rewrite_to": "$tyk_context.headers_X_My_Proxytourl",
                            "triggers": [],
                            "MatchRegexp": null
                        }
                    ]
```

If I just set the path/match_pattern back to `/.*` then it works

**Comment by furkansenharputlu** [comment] 2019-03-04 11:04
I tried it with your `applyRequestHeaders` method too and I couldn't reproduce the issue. I don't know maybe some other thing in your API definition can cause this.

**Comment by bitsofinfo** [comment] 2019-03-04 14:40
i'm going to move this over to the support channel

**Comment by bitsofinfo** [comment] 2019-03-08 14:38
I see a PR... any thoughts when this could get out into a release @buger ?

**Comment by buger** [comment] 2019-03-08 21:43
Not sure what is the proper way in such a situation. 

Code which broke your API was added to actually fix a bug when listen path conflicts with a path name. Previously Tyk was matching full request path, which was including listen path too. So lets say your listen_path is: "/my/listen/path/", and you have 2 paths explicitly defined in API (with different plugins), like: "/my" and "/test". When you try to query `/my/listen/path/test` path, Tyk tries to find if this endpoint has custom logic, e.g. defined in Endpoint designer, it goes through an array of all defined endpoints and tries to find a match. It starts with checking if "/my" match `/my/listen/path/test` and finds a false match: because listen path include the same part as path itself.

Now with a fixed version, it strips listen path during this check, so `/my/listen/path/test` becomes just `/test` and it matches the right endpoint. 

In your case, I have a feeling that you added endpoint match to include listen path too, to overcome this bug. And with this fix it is no longer needed: correct me if I wrong. 

However, I do get that it is kinda a breaking change. So maybe we should keep this change for 2.8, and leave 2.7 with original behavior. 

Happy to hear your thoughts.

**Comment by bitsofinfo** [comment] 2019-03-08 23:01
i guess I'm a bit confused now. If this PR is included a release... we are going to have to change.... what  exactly?

**Comment by adelowo** [comment] 2019-03-08 23:16
@bitsofinfo 2.7 is already released and semantic versioning doesn't allow for a 
breaking change in a patch release e.g `2.7.1`. So since this is a breaking change, it can only be
considered for `2.X` ( `2.8` in this case) not `2.X.Y` (`2.7.X`)

**Comment by bitsofinfo** [comment] 2019-03-09 04:57
Understood however I have the following questions:

1) It sounds like upgrading to 2.7.x is not going to be possible with existing API defs as currently defined and working with 2.6.4. IF I did want to migrate those API defs to 2.7.x what changes need to be made to the API defs to work in 2.7.x?

2) Otherwise: If I wait until 2.8.x is released (with this PR included), what changes will have to be made to my API defs to work w/ 2.8.x?

**Comment by buger** [comment] 2019-03-09 08:44
Not exactly. We have 2 PRs.
First which was already merged and released as part of 2.7.X, it broke @bitsofinfo APIs, and this ticket was created. PR created by Furkan is kinda rollback behavior of first PR.

So technically speaking we broke backward compatibility in this specific case with first PR, when “fixed” matching logic.

So our options are:
1. Merge @Furkan PR (e.g. rollback), and consider this bug as a “feature”...
2. Rollback in 2.7.x branch but keep this “breaking” bug fix in 2.8
3. Do nothing and affected users had too modify their APIs


Regarding way to adopt existing apis, you just need to exclude listen path from your urls when you url paths in API definition.

**Comment by bitsofinfo** [comment] 2019-03-10 16:56
> Regarding way to adopt existing apis, you just need to exclude listen path from your urls when you url paths in API definition.

Can you please explain? I don't follow this. So for 2.7.x we need to exclude listen path from what property/section specifically in an API def?

**Comment by bitsofinfo** [comment] 2019-03-12 19:19
Ok so for 2.7.x "as-is" any of these url-rewriters would would have to be replaced with `/` or `/.*` 

For 2.8.x (assuming this is "fixed") they can go back to the `/my/\\d.\\d/oauth/token` format...

correct?

**Comment by furkansenharputlu** [comment] 2019-03-13 13:10
@bitsofinfo I am closing this issue. The current behavior will stay same. You will change your API definition.

**Closed by furkansenharputlu** 2019-03-13 13:10 UTC
Labels: Priority: High, bug, customer request

**Comment by bitsofinfo** [comment] 2019-03-13 21:34
For anyone else coming across this problem, the issue is that the `paths` in scope of anything under endpoint designer (i.e. whitelists/urlrewrites) are intended to be *relative* from the slug... not inclusive of the slug.

**Comment by marksou** [comment] 2019-03-14 11:45
Hi @bitsofinfo we have updated the docs to clarify that paths, etc are relative. There are also UX changes in the Endpoint Designer going to be made to reflect this so it's clearer.
