### ISSUE TITLE
[TT-2385] - [logging] Ability to record RAW response for 4xx and 5xx errors

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2495] opened 2019-09-10 07:46 UTC
**Is your feature request related to a problem? Please describe.**

It is not recommended to enable raw request/response body logging in production. Space + Performance.

However for error scenarios e.g. 4xx & 5xx errors, it is often useful to be able to record the entire request/response body.

**Describe the solution you'd like**

Allow a config option to enable detailed recording only for errors.

**Comment by asoorm** [comment] 2020-03-29 20:47
not stale

**Comment by john-doe-2016** [comment] 2020-06-19 13:15
I agree, and to take it further, being able per api to choose to log the request parameters, the requests payloads or the the responses for security reasons but still be able to look for some specific activities (support for example).

And it is not directly related, but being able to see the result of url rewriting in those logs would be greatly helpful when dealing with regexps.

**Comment by andyo-tyk** [comment] 2023-04-03 15:14
This is logged on our product roadmap along with other suggestions around improving the flexibility of analytics; the future direction of Tyk is towards a more rounded observability solution using Open Telemetry, so this may be picked up in that work.
I will update this ticket as and when we implement something.
Thank you for supporting Tyk.

**Comment by andyo-tyk** [comment] 2023-05-22 16:54
I've realised that this is a duplicate of https://github.com/TykTechnologies/tyk/issues/2491, so we will continue to track the suggestion in that ticket.

**Closed by andyo-tyk** 2023-05-22 16:54 UTC
Labels: enhancement, manage-squad, zendesk
