### ISSUE TITLE
Not able to create new Key

### ISSUE THREAD

**Issue by alexforever86** [TykTechnologies/tyk#258] opened 2016-06-06 11:39 UTC
After installing Tyk Dashboard and Gateway (docker installation) & creating a new API, tried to create  a new key.  But, I'm getting the following error. 

`Failed to save new session object to Tyk: Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF`

**Comment by alexraju** [comment] 2016-06-06 11:43
I think gateway and dashboard is not able to communicate with each other or with MongoDB or redis elasticache. 

Dashboard logs:

```
time="Jun  6 10:55:35" level=info msg="Using /opt/tyk-dashboard/tyk_analytics.conf for configuration" 
time="Jun  6 10:55:35" level=info msg="Creating new Redis connection pool" 
time="Jun  6 10:55:35" level=info msg="Creating new Redis connection pool" 
time="Jun  6 10:55:35" level=info msg="Creating new Redis connection pool" 
time="Jun  6 10:55:35" level=info msg="Creating new Redis connection pool" 
time="Jun  6 10:55:35" level=info msg="Adding available nodes..." 
time="Jun  6 10:55:35" level=info msg="Tyk Analytics Dashboard 1.1.0.0" 
time="Jun  6 10:55:35" level=info msg="Copyright Martin Buhr 2016" 
time="Jun  6 10:55:35" level=info msg="https://www.tyk.io" 
time="Jun  6 10:55:35" level=info msg="Listening on port: 3000" 
time="Jun  6 10:55:35" level=info msg="Loading routes..." 
time="Jun  6 10:55:35" level=info msg="Registering nodes..." 
time="Jun  6 10:55:35" level=info msg="Creating new Redis connection pool" 
time="Jun  6 10:55:35" level=info msg="Adding available nodes..." 
time="Jun  6 10:55:35" level=info msg="Socket server started" 
time="Jun  6 10:55:35" level=info msg="--> Standard listener (http)" 
time="Jun  6 10:55:38" level=error msg="Failure in org lookup" 
time="Jun  6 10:55:38" level=error msg="not found" 
time="Jun  6 10:57:07" level=error msg="Nonce failed! Node:d1680fa1-12db-4f7a-57e4-d6e41c5b417f Nonce was:ZDE2ODBmYTEtMTJkYi00ZjdhLTU3ZTQtZDZlNDFjNWI0MTdmOGQzY2YwYTBlYjEzNDgwMTZjNGUyOGMyNjE4ODAxZDk= Should be: ZDE2ODBmYTEtMTJkYi00ZjdhLTU3ZTQtZDZlNDFjNWI0MTdmNmQ1OTgwMWY5YjU1NDkzZTQ2NWVjNjhjNTU4ZDkwZmU=" 
time="Jun  6 11:11:44" level=error msg="Failure in org lookup" 
time="Jun  6 11:11:44" level=error msg="not found" 
time="Jun  6 11:14:32" level=error msg="Failure in org lookup" 
time="Jun  6 11:14:32" level=error msg="not found" 
time="Jun  6 11:14:32" level=error msg="Failure in org lookup" 
time="Jun  6 11:14:32" level=error msg="not found" 
time="Jun  6 11:14:32" level=error msg="Couldn't retrieve organisation!" 
time="Jun  6 11:14:32" level=error msg="Failed tp update register!" 
time="Jun  6 11:15:06" level=warning msg="Failed to retrieve object: not found" 
time="Jun  6 11:15:38" level=warning msg="User pasword is empty! Please reset!" 
time="Jun  6 11:15:38" level=info msg="New user session created" 
time="Jun  6 11:15:42" level=info msg="Sending notification{ApiUpdated d30297bb4510474856ade1274859dad6}" 
time="Jun  6 11:15:42" level=info msg="Sending notification{ApiUpdated c12f1adf0cdf46cc69c41d3b000bb715}" 
time="Jun  6 11:15:42" level=info msg="Sending notification{ApiUpdated d11a08c74e13409d43b0cbe8e5f2d2c5}" 
time="Jun  6 11:17:14" level=info msg="New user session created" 
time="Jun  6 11:17:37" level=info msg="Sending notification{ApiUpdated 17fc4124d60742bb63b37affd25f8e76}" 
time="Jun  6 11:17:47" level=error msg="Something went wrong, couldn't get Api list" 
time="Jun  6 11:17:47" level=error msg="read tcp 172.17.0.2:34882->1.1.1.1:27017: read: connection reset by peer" 
time="Jun  6 11:17:47" level=info msg="Attempting to reconnect" 
time="Jun  6 11:18:07" level=error msg="No nodes available" 
time="Jun  6 11:18:12" level=error msg="No nodes available" 
time="Jun  6 11:18:17" level=error msg="No nodes available" 
time="Jun  6 11:18:22" level=error msg="No nodes available" 
time="Jun  6 11:18:27" level=error msg="No nodes available" 
time="Jun  6 11:18:32" level=error msg="No nodes available" 
time="Jun  6 11:18:37" level=error msg="No nodes available" 
time="Jun  6 11:18:42" level=error msg="No nodes available" 
time="Jun  6 11:18:47" level=error msg="No nodes available" 
time="Jun  6 11:18:52" level=error msg="No nodes available" 
time="Jun  6 11:18:57" level=error msg="No nodes available" 
time="Jun  6 11:19:02" level=error msg="No nodes available" 
time="Jun  6 11:19:07" level=error msg="No nodes available" 
time="Jun  6 11:19:12" level=error msg="No nodes available" 
time="Jun  6 11:19:17" level=error msg="No nodes available" 
time="Jun  6 11:19:22" level=error msg="No nodes available" 
time="Jun  6 11:19:27" level=error msg="No nodes available" 
time="Jun  6 11:34:32" level=error msg="Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 
time="Jun  6 11:34:32" level=warning msg="Failed create:Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 
time="Jun  6 11:34:32" level=error msg="Failed to save new session object to Tyk: Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 

```

**Comment by alexraju** [comment] 2016-06-06 11:46
Gateway logs: 

```
time="Jun  6 10:57:07" level=info msg="Connection dropped, connecting.." 
time="Jun  6 10:57:07" level=warning msg="Cache purging is no longer part of Tyk Gateway, please use Tyk-Pump." 
time="Jun  6 10:57:07" level=info msg="Starting Poller" 
time="Jun  6 10:57:07" level=info msg="Setting up Server" 
time="Jun  6 10:57:07" level=info msg="--> Standard listener (http)" 
time="Jun  6 10:57:07" level=info msg="Registering node." 
time="Jun  6 10:57:07" level=info msg="Node registered" id=d1680fa1-12db-4f7a-57e4-d6e41c5b417f 
time="Jun  6 10:57:07" level=info msg="Starting heartbeat." 
time="Jun  6 10:57:07" level=info msg="Detected 0 APIs" 
time="Jun  6 10:57:07" level=info msg="Loading uptime tests..." 
time="Jun  6 10:57:07" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.DBPolicy" 
time="Jun  6 10:57:07" level=info msg="Gateway started (v2.1.0.2)" 
time="Jun  6 10:57:07" level=info msg="--> Listening on port: 8080" 
time="Jun  6 11:15:42" level=info msg="Reloading endpoints" 
time="Jun  6 11:15:42" level=info msg="Initiating reload" 
time="Jun  6 11:15:42" level=info msg="Reloading endpoints" 
time="Jun  6 11:15:42" level=info msg="Reloading endpoints" 
time="Jun  6 11:15:52" level=info msg="Detected 4 APIs" 
time="Jun  6 11:15:52" level=info msg="--> Loading API: Portal Assets" 
time="Jun  6 11:15:52" level=info msg="----> Tracking: store-prod-agent-elb-665374692.ap-northeast-1.elb.amazonaws.com" 
time="Jun  6 11:15:52" level=info msg="----> Checking security policy: Open" 
time="Jun  6 11:15:52" level=info msg="--> Loading API: Portal API" 
time="Jun  6 11:15:52" level=info msg="----> Tracking: store-prod-agent-elb-665374692.ap-northeast-1.elb.amazonaws.com" 
time="Jun  6 11:15:52" level=info msg="----> Checking security policy: Open" 
time="Jun  6 11:15:52" level=info msg="--> Loading API: Portal" 
time="Jun  6 11:15:52" level=info msg="----> Tracking: store-prod-agent-elb-665374692.ap-northeast-1.elb.amazonaws.com" 
time="Jun  6 11:15:52" level=info msg="----> Checking security policy: Open" 
time="Jun  6 11:15:52" level=info msg="--> Loading API: test api" 
time="Jun  6 11:15:52" level=info msg="----> Tracking: (no host)" 
time="Jun  6 11:15:52" level=info msg="----> Checking security policy: Token" 
time="Jun  6 11:15:52" level=info msg="Loading uptime tests..." 
time="Jun  6 11:15:52" level=info msg="API reload complete" 
time="Jun  6 11:17:37" level=info msg="Reloading endpoints" 
time="Jun  6 11:17:37" level=info msg="Initiating reload" 
time="Jun  6 11:17:47" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.ResponseStruct" 
time="Jun  6 11:17:47" level=info msg="--> Retrying in 20s" 
time="Jun  6 11:18:07" level=warning msg="Reloader timed out! Removing sentinel" 
time="Jun  6 11:18:07" level=info msg="Registering node." 
time="Jun  6 11:18:07" level=error msg="Failed to register node, retrying in 5s" 
time="Jun  6 11:18:12" level=error msg="Failed to register node, retrying in 5s" 
time="Jun  6 11:18:17" level=error msg="Failed to register node, retrying in 5s" 
time="Jun  6 11:33:18" level=warning msg="Key not found in storage engine" err="Key not found" inbound-key=null 
time="Jun  6 11:33:18" level=info msg="Attempted access with non-existent key." key=null origin=172.17.0.1 path="/test-api/get" 
2016/06/06 11:34:25 http: panic serving 10.0.2.140:42502: runtime error: invalid memory address or nil pointer dereference
goroutine 241 [running]:
net/http.(*conn).serve.func1(0xc820206480)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xc90e00, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.createKeyHandler(0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/home/tyk/go/src/github.com/lonelycode/tyk/api.go:1315 +0x141b
main.CheckIsAPIOwner.func1(0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc8200fccd0, 0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203085a0, 0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc8204d5170, 0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8203c4300, 0x7f28867eb5d8, 0xc82012eb60, 0xc82038b180)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820206480)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
time="Jun  6 11:34:28" level=error msg="Failed to register node, retrying in 5s" 
time="Jun  6 11:34:29" level=info msg="Reset quota for key." inbound-key=57555b59e15737000100000354bfd8f0a41747854b9c2ab7722f3bf7 key=quota-5d45d082 
```

**Comment by alexraju** [comment] 2016-06-06 11:48
@lonelycode, it would be great if you could take a look at this.

**Comment by lonelycode** [comment] 2016-06-06 13:29
Lots of these errors look networking related? 

Also, if you are trying to create a key for an Open API or non-live API you'll get problems, I think that panic is for an API that doesn't exist or may have been skipped. Tyk will only create keys for APIs that are live.

It looks like you have some serious connectivity issues, how are these instances networked?

Are you starting more than one gateway?

Are you adding or editing APIs as a super user? If you are, don't, perform all operations *within an organisation*, you get wierd behaviour if you create things as a super user, they are for monitoring only.

**Comment by alexraju** [comment] 2016-06-06 14:26
@lonelycode 

Created the Key for a simple API just created.

The gateway and dashboard instances are docker containers in a cluster and I checked connection between gateway and dashboard from each of the containers. 

There is only 1 instance of gateway. But, I have been re-installing Tyk components multiple times. 

If you meant admin user by super user, yes, I created the API, token etc as a super user. Could you please elaborate on "you get wierd behaviour if you create things as a super user, they are for monitoring only."

Also, I have been trying to understand the errors. 
*From Dashboard log*
1) What does "Nonce failed! Node:d1680fa1-12db-4f7a-57e4-d6e41c5b417f Nonce was:ZDE....= Should be: ZDE2O.........kwZmU=" means?
2) 
```
time="Jun  6 11:34:32" level=error msg="Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 
time="Jun  6 11:34:32" level=warning msg="Failed create:Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 
time="Jun  6 11:34:32" level=error msg="Failed to save new session object to Tyk: Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF" 
```
Does this mean any communication issues (b/w dashboard & gateway or b\w dashboard & mongodb/redis)?

3) In log, `"Registering nodes..." ` , means dashboard node is registered. And later `"No nodes available" ` means something happened to the the registered node. Does this mean connectivity issue between dashboard and gateway?

* From gateway log*
4) Initial error log from gateway is `msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.DBPolicy" `. What could be the reason for this?

5) Does error `http: panic serving 10.0.2.140:42502: runtime error: invalid memory address or nil pointer dereference` means a connectivity issue with redis?

Also, I have another queries. Please give a quick response. 

* We are using MongoDB for storing analytical data only. right? So, can we run Tyk without MongoDB?

@lonelycode  Appreciate very much for your help

**Comment by lonelycode** [comment] 2016-06-06 14:39
Super users: are not all controlling entities, they can see and modify some data on a Tyk installation but should not be used for anything except bootstrapping an organisation and a regular user. That's all there is to it, if you do stuff as a super user, you basically create non-owned APis and keys and policies and Tyk isn't meant to be used that way, so you get surprising behaviour.

Bottom line: don't use a super user, instead restrict existing users by using the within-orgs permissions.

2) Nonce failed means that the Tyk gateway call tk the dashboard had an invalid nonce and so the request is rejected. Tyk uses a nonce for eachgateway interaction to keep track of gateways and ensure comms is secure. It's between gateway and dashboard

3) Registering nodes means unpacking your license, it has nothing to do with your connected gateways

4) the reason is an access denied message that isn't decoded (this can happen in a bootstrapped first run, it fixes as soon as you save your first policy or API 

5) no it means that Tyk tried to find an API spec that doesn't exist to access it's backend DB reference and since it's not there it fell back to a secondary handler which wadnyltnintiialised properly, it's a known bug - and you're probably only seeing it because of a misconfiguration (creating a key on anon existent API)

5) if you are using the dashboard for anything you need MongoDB, it's not optional for the dashboard (and that means for a Pro install too)

**Comment by alexraju** [comment] 2016-06-06 14:50
By the way, I created the user under an organisation using the initial script. So, I guess it wasn't a super user.

**Comment by lonelycode** [comment] 2016-06-06 14:51
Ok, then the API you were granting access to wasn't loaded

**Comment by alexraju** [comment] 2016-06-06 15:18
Just adding...
Key creation succeeded once. No idea, how it happened. Following error were shown in UI for the rest of the tries.
`Failed to save new session object to Tyk: Failed to create key: Post http://1.1.1.1:3001/tyk/keys/create: EOF`

And this caused because of an error in gateway while handling the request (Post http://1.1.1.1:3001/tyk/keys/create) from dashboard

See the gateway log.
```
time="Jun  6 15:16:40" level=info msg="Reset quota for key." inbound-key=57555b59e1573700010000032199403b060a471179a28396187d8a87 key=quota-ad22e073 
2016/06/06 15:16:40 http: panic serving 10.0.2.138:40934: runtime error: invalid memory address or nil pointer dereference
goroutine 258 [running]:
net/http.(*conn).serve.func1(0xc820312a00)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xc90e00, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.createKeyHandler(0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/home/tyk/go/src/github.com/lonelycode/tyk/api.go:1315 +0x141b
main.CheckIsAPIOwner.func1(0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc8202c3100, 0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82023cf00, 0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc82057d800, 0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8202f2380, 0x7f3197583a28, 0xc82006a270, 0xc8202f02a0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820312a00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

```

**Comment by roryblucky** [comment] 2016-08-16 06:39
I met same error with alexraju. From my side, the api-gateway and dashboard  are on the same machine. Any ideas?
@lonelycode it would be great if you could take a look at this

**Comment by alexraju** [comment] 2016-08-16 06:43
@roryblucky For me, it was an issue related to Tyk setup in DC/OS. I fixed this with running `sudo sysctl -w net.netfilter.nf_conntrack_tcp_be_liberal=1` on my CoreOS machine.

**Comment by roryblucky** [comment] 2016-08-16 06:53
@alexraju Thanks for you help,but it seems not wok for me. :(

My env is  ubuntu 14.04 LTS on Azure cloud

**Comment by alexraju** [comment] 2016-08-16 07:19
@roryblucky The core reason was that my gateway wasn't able to communicate with the dashboard. You need to see if this is the case with you as well. Trying pinging your dashboard from within your gateway container and vice versa.

**Comment by james-tyk** [comment] 2016-08-16 07:37
Hi @roryblucky 

You will likely find the answer here: https://community.tyk.io/search?q=Failed%20to%20create%20key

Typically this is because, as @alexraju suggested, the gateway and dash can't see each other.
For support/queries, I'd suggest using community.tyk.io, its free, there is a large and very smart community present and the Tyk team get involved too.

We try to keep Github for bugs, etc.

Thanks


James@tyk.io

**Comment by roryblucky** [comment] 2016-08-16 08:04
@alexraju @james-tyk The wired things is the dash and api gateway on the same machine, and the urls are 127.0.0.1:3000 127.0.0.1:8080, I am confused that why they cannot see each other??

thank for your remind, I will post the questions to the community later if we cannot fix it. :0

**Comment by lonelycode** [comment] 2016-08-16 08:10
You could try using `localhost` instead of the IP loopback. Also, the [forum](https://community.tyk.io) would be a better place for this as Github is mainly for bug reports, not software support.

**Comment by penhauer-xiao** [comment] 2016-10-30 05:56
I have seen this problem, each time after several operations are repeated successfully. I continue to focus on this issue.

**Comment by kohrVid** [comment] 2017-01-24 11:24
Hi @penhauer-xiao,

Apologies for the delayed response. Are you still unable to create new keys on the latest version of the Tyk Dashboard? If so, have you tried any of the suggestions made @alexraju, @james-tyk or @lonelycode? If you are in fact now able to create new keys, could you please confirm so that we can close this issue on Github?

Kind regards,
Jess @ Tyk

**Comment by mvdan** [comment] 2017-02-16 14:20
@penhauer-xiao I'm closing this issue now - if you're still having the same problem or would like any more help, feel free to reopen with more information.

Thanks.

**Closed by mvdan** 2017-02-16 14:20 UTC

**Comment by penhauer-xiao** [comment] 2017-02-17 12:20
Thanks all, I know the reason, when adding a new API, DGateway cluster to complete 10 seconds to complete, if 10 seconds to create the key about this API,  it will have this problem.

**Comment by mvdan** [comment] 2017-02-17 12:22
Thanks for the update! Glad you sorted it out.

**Comment by penhauer-xiao** [comment] 2017-02-17 12:28
I think to wait for 10 seconds is too long, each time to add or modify an API, you need to slowly read the seconds until 10; wait 10 seconds before you can edit the Policy, to just add the new API.

**Comment by mvdan** [comment] 2017-02-17 12:31
@penhauer-xiao could you please post on community.tyk.io with full details on your setup and how to reproduce the issue? We can take it back here on the tracker once it's clear that there is a bug to be fixed.

Thanks!
