### ISSUE TITLE
Use Tyk REST API endpoint to update policies.json

### ISSUE THREAD

**Issue by haoyuanli** [TykTechnologies/tyk#2960] opened 2020-03-25 21:36 UTC
**Is your feature request related to a problem? Please describe.**
A feature

**Describe the solution you'd like**
A very simple POST API endpoint, that always writes the JSON body  of the POST request to be the new definition of the specified policies.json, (location specified in tyk.conf)

This enables us to update APIs without having to write the files directly. Currently, we can create APIs, keys using Tyk Rest API, just not policies.

**Describe alternatives you've considered**
none

**Additional context**
This enables us to update APIs without having to write the files directly. Currently, we can create APIs, keys using Tyk Rest API, just not policies.

**Comment by mcandre** [comment] 2020-04-01 19:09
Duplicate of #2379

**Comment by christtyk** [comment] 2020-04-14 15:12
Thanks for the report. We will continue discussions on #2379

**Comment by agata-wit** [comment] 2021-07-16 12:50
Closing this as duplicate. Please see https://github.com/TykTechnologies/tyk/issues/2379 for continued discussion

**Closed by agata-wit** 2021-07-16 12:50 UTC
Labels: enhancement
