### ISSUE TITLE
[TT-2701] Unable to use colon in `TYK_GW_SECRETS` environment variable

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#3590] opened 2021-06-21 04:16 UTC
**Branch/Environment/Version**
- Branch/Version: v3.1.2 (but expect present in all recent versions)
- Environment: any

**Describe the bug**
Cannot include `:` character in values defined in `TYK_GW_SECRETS` environment variable, as the `:` is a separator between key and value, so using in the value itself causes a fatal error when Gateway boots:

```
time="Jun 18 06:56:39" level=fatal msg="Error initialising system: failed to process config env vars: envconfig.Process: assigning TYK_GW_SECRETS to Secrets: converting 'target_url:http://httpbin.org,listen_path:/secret-path/,header:secret-header-value' to type map[string]string. details: invalid map item: "target_url:http://httpbin.org"" prefix=main
```

In this case, I am trying to use the secret `target_url` to set the target URL in an API Definition via a Docker Compose file:

```
services:
  tyk-gateway:
    environment:
      - TYK_GW_SECRETS=target_url:http://httpbin.org
```

**Reproduction steps**

1. Add API Definition that uses a secret to set the target URL:
```
"proxy": {
    "target_url": "secrets://target_url",
    ...
}
```

2. Use Gateway environment variable to set the secret:
```
TYK_GW_SECRETS=target_url:http://httpbin.org
```

3. Attempt to boot Gateway results in error:
`Error initialising system: failed to process config env vars`

**Actual behavior**
Colons cannot be used in secret values when specified as an environment variable.

**Expected behavior**
Colons can be used in secret values when specified as an environment variable.

Perhaps the secrets need to be encoded, to enable reserved characters to be used.

**Screenshots/Video**
n/a

**Logs (debug mode or log file):**
n/a

**Configuration (tyk config file):**
n/a

**Additional context**
n/a

**Comment by komuw** [comment] 2021-07-16 13:06
I spent sometime having a look at this. 

This looks like an issue with one of the dependencies of `tyk`, specifically: https://github.com/kelseyhightower/envconfig

Here is a small reproducer of the issue.
```go
package main

import (
	"fmt"
	"os"

	"github.com/kelseyhightower/envconfig"
)

type MyConf struct {
	// Secrets are key-value.
	Secrets map[string]string `json:"secrets"`
}

func main() {
	os.Setenv("TYK_GW_SECRETS", "target_url:http://httpbin.org")

	envPrefix := "TYK_GW"
	conf := &MyConf{Secrets: map[string]string{}}

	err := envconfig.Process(envPrefix, conf)
	if err != nil {
		panic(err)
	}

	fmt.Println("\n\t everything went ok.")
}
```

I found a number of requests in that repository asking for a fix: https://github.com/kelseyhightower/envconfig/search?q=colon&type=issues    
And someone had even sent a PR to try and resolve it: https://github.com/kelseyhightower/envconfig/pull/136    
but that PR was not merged.    

This comment talks about using a custom decoder; https://github.com/kelseyhightower/envconfig/issues/84#issuecomment-330276369 but I haven't investigated how feasible that would be.

**Comment by andyo-tyk** [comment] 2023-08-17 15:09
Closing here - we will continue to track internally, but are hampered by dependency.

**Closed by andyo-tyk** 2023-08-17 15:09 UTC
Labels: bug, manage-squad
