### ISSUE TITLE
[TT-2018] - go module not functioning.

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3351] opened 2020-10-06 19:07 UTC
With Tyk v3.0.1, the go module implementation has multiple breaking problems.

`go mod download` fails when you attempt to import the library at v3.0.1 into another Go module project.

`go mod download` corrupts the request for v3.0.1 into "v0.0.0-20200831104105-68f450e386a9".

That's with Go v1.12, which has gaps in checking go module integrity. Newer versions, such as Go 1.13, note that the library fails to properly prefix the import paths according to official go module standards.

**Comment by Moses-oyedeji** [comment] 2021-06-28 18:09
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by vverbani** [comment] 2022-06-14 17:08
Hi @mcandre, just an update on this. We've since moved away from v1.12 and into v1.15 with the newer Tyk versions. Closing this as a result.

**Closed by vverbani** 2022-06-14 17:08 UTC
Labels: bug, zendesk
