### ISSUE TITLE
MW validate json, incorrect json structure 

### ISSUE THREAD

**Issue by ignashkins** [TykTechnologies/tyk#4770] opened 2023-02-13 19:21 UTC
**Branch/Environment/Version**
- all version up to 4.3.2 (we use 3.2.2 && 4.3.2)

**Describe the bug**
We detected an incorrect JSON response format in the answer.
Single quotes are subsequently escaped and this breaks the structure.

The process is reflected in the skinshots.

**Reproduction steps**

1. Set up middleware json request validation
2. Configure template string validation 
3. Execute erroneous request

**Actual behavior**
Not valid JSON structure

**Expected behavior**
Valid JSON structure

**Screenshots/Video**
![2023-02-13_22-13-06](https://user-images.githubusercontent.com/2168065/218553333-52280345-4e49-4936-9edb-defd29c3a24a.png)
![2023-02-13_22-06-42](https://user-images.githubusercontent.com/2168065/218553343-93e2f154-db36-413b-b8c9-c27cefbdc31d.png)
![2023-02-13_22-05-02](https://user-images.githubusercontent.com/2168065/218553345-640d0f7d-4200-485d-b575-5fcb68def46e.png)
![2023-02-13_22-04-13](https://user-images.githubusercontent.com/2168065/218553349-ad2bf19e-b335-4683-9cfb-b3a3e3c4e5ca.png)

**Logs (debug mode or log file):**
We did not see this problem in the logs
`time="Feb 13 22:11:56" level=debug msg=Finished api_id=8fd47a01e40f4c5481ab9d953b4e37e8 api_name="Middleware" code=422 error="receiverId.mobilePhone: String length must be less than or equal to 3; receiverId.mobilePhone: Does not match pattern '(7[0-9]{10})$'" key="****In0=" mw=ValidateJSON ns=747439274`

**Configuration (tyk config file):**
By request

**Additional context**
By request

**Comment by oluwaseyeayinla** [comment] 2023-03-13 14:28
@ignashkins Can you share your API definition file and your HTTP call? I am unable to reproduce the issue on v3.2.2 and v4.3.2.

The response about string length is a bit weird. I was only able to reproduce the error when the `maxLength` is set to 3. You may want to ensure you are calling the correct path.  

Also the regex syntax is in golang and the result looks fine to me. The pattern does not match since the first number should begin with seven (7) instead of 0 (zero).

**Comment by oluwaseyeayinla** [comment] 2023-03-13 15:20
I just looked at it again and I understand now it's the single quote in the response you are talking about. I'll close this since an earlier one was opened about the same incident https://github.com/TykTechnologies/tyk/issues/4363.

**Closed by oluwaseyeayinla** 2023-03-13 15:20 UTC
Labels: bug
