### ISSUE TITLE
Python Custom Bundle Tests

### ISSUE THREAD

**Issue by odiliacermati** [TykTechnologies/tyk#3369] opened 2020-10-23 08:39 UTC
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: 

**Describe the bug**
Hi! So I'm trying to create a test for a response hook plugin that I wrote in python. No matter how simple I made the plugin (immediately return response), I keep getting a 500 error when running the test (`"error": "Middleware error"`), so i tried to run one of your tests for python bundles in `coprocess/python/coprocess_python_test.go` and getting the same middleware error on the response hook one.

**Reproduction steps**

run the TestPythonBundldes test
```
cd coprocess/python
go test -v -run TestPythonBundles
```

**Actual behavior**
Test failed with `{ "error": "Middleware error" }` message for "Single-file bundle with response hook"

**Expected behavior**
Test passing

**Screenshots/Video**
n/a

**Logs (debug mode or log file):**
```
go test -v -run TestPythonBundles

=== RUN   TestPythonBundles
=== RUN   TestPythonBundles/Single-file_bundle_with_response_hook
    http.go:270: [0] Expected status code `200` got `500. {
            "error": "Middleware error"
        }`.
```

**Configuration (tyk config file):**
n/a

**Additional context**
n/a

Thank you!

**Comment by christtyk** [comment] 2021-03-01 14:15
Hey @matiasinsaurralde can you help here?

**Comment by andyo-tyk** [comment] 2023-03-21 14:25
We're not able to reproduce this on latest supported Tyk, so I will close this ticket.

If you still have this problem on Tyk 4.x, please do not hesitate to re-open and we will investigate further.

Thank you for supporting Tyk!

**Closed by andyo-tyk** 2023-03-21 14:25 UTC
Labels: bug, zendesk
