### ISSUE TITLE
With bind to slugs enabled, Hybrid does not track endpoint analytics. This works in cloud and on-prem

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1270] opened 2017-11-07 19:27 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Tracked endpoints do not show up in the analytics when in hybrid mode

**What is the expected behavior?**
Tracked endpoints should appear in hybrid mode

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create an open API
2. Add tracked endpoints to it
3. Send traffic to a slaved gateway (Bind to slugs must be enabled)
4. No analytics

If you send the same request to our cloud endpoint, the request is tracked properly.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Hybrid, potentially MDCB slave (MDCB was not tested)

**Comment by ilijabojanovic** [comment] 2018-01-19 09:41
This issue has been resolved with latest pump release

**Closed by ilijabojanovic** 2018-01-19 09:41 UTC
Labels: Ready for development, bug

**Comment by buger** [comment] 2018-01-19 09:42
I think you meant MDCB release?

**Comment by ilijabojanovic** [comment] 2018-01-19 10:48
@buger Yes, i can't reproduce this issue anymore on production. Now tracking working as expected
