### ISSUE TITLE
TCP proxy: Analytics records data constantly for tcp proxy api's

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2561] opened 2019-09-26 10:32 UTC
**Branch/Environment/Version**
- Branch/Version: Release-2.9
- Environment: All

**Describe the bug**
When we create api def with tcp proxy, gateway constantly records data and fill pump with/without traffic to gateway

**Reproduction steps**

1. Create tcp proxy api definition
2. Check gateway logs

**Actual behavior**
Pump constantly records data in mongodb 

**Expected behavior**
We should record only real traffic

**Screenshots/Video**
<img width="1901" alt="Screen Shot 2019-09-26 at 12 19 58 PM" src="https://user-images.githubusercontent.com/8557292/65681627-98b1a180-e059-11e9-86cb-d400e8284ef4.png">

**Logs (debug mode or log file):**
Pump
```
[Sep 26 12:23:29]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:29]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:31]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:31]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:33]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:33]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:35]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:35]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:37]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:37]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:39]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:39]  INFO mongo-pump-aggregate: Writing 2 records
[Sep 26 12:23:41]  INFO mongo-pump: Purging 2 records
[Sep 26 12:23:41]  INFO mongo-pump-aggregate: Writing 2 records
```
**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by buger** [comment] 2019-09-26 15:52
This is fine to have special record per second. 
The real bug here https://github.com/TykTechnologies/tyk-analytics-ui/issues/1475

**Comment by ilijabojanovic** [comment] 2019-09-26 19:33
@buger this issue is still visible, with latest pump and analytics

**Comment by buger** [comment] 2019-09-26 19:51
I mean it is totally expected. What you see is not a bug. Each API generate 1 record per second. 

And Pump change fixed https://github.com/TykTechnologies/tyk-analytics-ui/issues/1475

**Comment by ilijabojanovic** [comment] 2019-09-27 09:26
@buger  `"ResponseCode":-1,` is still visible in analytics logs

**Comment by gernest** [comment] 2019-10-03 10:17
@ilijabojanovic I think you might have run tests against older commits of the tyk-pump. I have verified using the current tyk-pump master branch `a0c5b2c28f07bdb58adc08bc7a7e69526234cddc`   that this issue is resolved.

**Comment by ilijabojanovic** [comment] 2019-10-03 14:50
This issue is still visible on our testing env.

**Comment by buger** [comment] 2019-10-03 19:28
I found the issue.

It is partly problem with our dev env confing for pump, and for sure pump bug too.

"mongo" pump itself was fixed, but "mongo-selective" pump not, that why it was still visible on test env...

Fixed now.

**Closed by buger** 2019-10-03 19:28 UTC
Labels: bug

**Comment by maciejwojciechowski** [comment] 2019-10-03 19:44
confirmed, fixed
-1 not shown anymore on UI

![image](https://user-images.githubusercontent.com/39672152/66158803-eb292a00-e626-11e9-9794-8f2766b7c811.png)
