### ISSUE TITLE
 Invalid token is allowed.

### ISSUE THREAD

**Issue by minicats** [TykTechnologies/tyk#319] opened 2016-11-17 10:02 UTC
make token : 582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902

1. Good
```
curl -X GET http://localhost:8080/ttt/test2/
{
    "error": "Authorization field missing"
}
```

2. Good
```
curl -X GET -H "Authorization: 582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902"  http://localhost:8080/ttt/test2/
{"a":"aaaa"}
```

3.  Invalid token is allowed.
```
curl -X GET -H "Authorization: 582929e980f54d08b8000001df0a5b48d06a4cd94902abd"  http://localhost:8080/ttt/test2/
{"a":"aaaa"}
```

**Comment by lonelycode** [comment] 2016-11-17 10:04
Interesting, thanks for letting us know - we'll investigate. If you truncate the token, it fails though am I correct?

**Comment by minicats** [comment] 2016-11-17 10:17
I am truncate  "582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902"

Good.
curl -X GET -H "Authorization: 582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902"
{
    "error": "Key not authorised"
}



new make key : 582929e980f54d08b80000012c8915265359488cb74fabdd

1. Good
curl -X GET -H "Authorization: 582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902" http://localhost:8080/ttt/test2/
{"a":"aaaa"}


2. Invalid token is allowed
curl -X GET -H "Authorization: 582929e980f54d08b8000001df0a5b48d06a4cd973c8d2f2f9724902abc" http://localhost:8080/ttt/test2/
{"a":"aaaa"}

**Comment by mvdan** [comment] 2017-01-30 10:26
@minicats does this still happen with 2.3.1? I can't reproduce it here.

**Comment by mvdan** [comment] 2017-02-02 10:26
@buger could you please try to reproduce this one too? Maybe I did something wrong or there's something I'm missing.

**Comment by ilijabojanovic** [comment] 2017-02-02 16:09
@buger @mvdan I can't reproduce issue on testing and staging environment

**Comment by buger** [comment] 2017-02-03 09:15
@minicats seems like it is was fixed in our latest stable version. If you try 2.3.1 and have the same bug feel free to re-open this issue. Also if you can give us full API spec (you can export it from Dashboard UI if you use on-premise version), or from `/apis` folder in Tyk gateway if you use it without a dashboard.

I'm closing it, for now, thanks everyone!

**Closed by buger** 2017-02-03 09:15 UTC
Labels: bug
