### ISSUE TITLE
[TT-1947] Untracked dependencies in v2.9.4.3

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3349] opened 2020-10-05 16:06 UTC
The golang.org/x/text/encoding dependency is missing from the vendor directory in 2.9.4.3:

https://github.com/TykTechnologies/tyk/tree/v2.9.4.3/vendor/golang.org/x

**Comment by Moses-oyedeji** [comment] 2021-06-28 18:37
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by christtyk** [comment] 2021-09-02 11:20
Closing as 2.9.4.3 is essentially out of support. IF still an issue in new versions please report.

**Closed by christtyk** 2021-09-02 11:20 UTC
Labels: bug, wontfix, zendesk
