### ISSUE TITLE
Concurrent read/write on variable of redigocluster library

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2081] opened 2019-01-23 13:15 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I found a read write race condition in the code. StartPubSubLoop goroutine is calling **_switchToSingleModeIfNeeded(_)** and main goroutine is calling **_SendClusterCommand()_**. Both methods are trying to access same variable of redigocluster library.

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Output of go run -race 
```console
WARNING: DATA RACE
Write at 0x00c0002c85e9 by goroutine 117:
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster.(*RedisCluster).switchToSingleModeIfNeeded()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster/rediscluster.go:161 +0x1dc
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster.(*RedisCluster).RandomRedisHandle()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster/rediscluster.go:240 +0x50c
  github.com/TykTechnologies/tyk/storage.RedisCluster.StartPubSubHandler()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/storage/redis_cluster.go:498 +0xc8
  main.startPubSubLoop()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/redis_signals.go:49 +0x7b

Previous read at 0x00c0002c85e9 by main goroutine:
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster.(*RedisCluster).SendClusterCommand()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster/rediscluster.go:554 +0x61
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster.(*RedisCluster).Do()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/redigocluster/rediscluster/rediscluster.go:671 +0x8b
  github.com/TykTechnologies/tyk/storage.RedisCluster.GetKey()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/storage/redis_cluster.go:216 +0x3b1
  github.com/TykTechnologies/tyk/storage.clusterConnectionIsOpen()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/storage/redis_cluster.go:47 +0x191
  github.com/TykTechnologies/tyk/storage.IsConnected()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/storage/redis_cluster.go:77 +0x479
  main.main()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/main.go:963 +0x395
  fmt.Sscan()
      /usr/local/go/src/fmt/scan.go:100 +0xb0
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain.Listener()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain/goagain.go:173 +0x105
  main.main()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/main.go:945 +0x2dc

Goroutine 117 (running) created at:
  main.start()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/main.go:1091 +0x3a9
  main.main()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/main.go:956 +0x33e
  fmt.Sscan()
      /usr/local/go/src/fmt/scan.go:100 +0xb0
  github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain.Listener()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain/goagain.go:173 +0x105
  main.main()
      /home/komal/GoWorkspace/src/github.com/TykTechnologies/tyk/main.go:945 +0x2dc
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by komalsukhani** [comment] 2019-01-23 13:36
I don't think so. Problem lies in storage/redis_cluster.go file. #2082 is changing api_loader.go file

**Comment by buger** [comment] 2019-01-23 13:59
Yes, I posted comment to wrong issue :)

**Comment by evityuk** [comment] 2019-02-01 15:52
Fixed in this https://github.com/TykTechnologies/redigocluster/pull/4/files
Look like duplicate of this `epic` https://github.com/TykTechnologies/product/issues/188 .
Please track this issue for details

**Closed** 2019-05-09 10:11 UTC
