### ISSUE TITLE
cannot convert func literal

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#813] opened 2017-06-17 10:03 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

github.com/TykTechnologies/tyk/vendor/github.com/rs/cors
vendor/github.com/rs/cors/cors.go:215: cannot convert func literal (type func("github.com/TykTechnologies/tyk/vendor/golang.org/x/net/context".Context, http.ResponseWriter, *http.Request)) to type xhandler.HandlerFuncC

**What is the expected behavior?**

To build it is ok

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

$git:(master*) go build

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

master branch

**Comment by mvdan** [comment] 2017-06-17 16:13
What Go version are you on? Master builds fine on 1.7 and later, as enforced by CI.

**Comment by penhauer-xiao** [comment] 2017-06-17 22:49
@mvdan  Master builds fine on Go 1.8.3

**Comment by penhauer-xiao** [comment] 2017-06-17 22:50
# https://github.com/rs/cors/issues/36#issuecomment-309226291

**Comment by mvdan** [comment] 2017-06-17 23:18
You say master builds fine on 1.8, so I really don't know what the issue is here.

Whether or not a library we use broke backwards compatibility is also irrelevant, as we vendor all dependencies.

Closing this, as I see nothing to fix.

**Closed by mvdan** 2017-06-17 23:18 UTC
